<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>ShouTech.Core.Inv</AssemblyName>
    <RootNamespace>ShouTech.Core.Inv</RootNamespace>
    <Version>10.3.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ShouTech.Domain\ShouTech.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.44" />
    <PackageReference Include="Npgsql" Version="8.0.6" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.2" />
  </ItemGroup>

</Project>