-- â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
-- FILE: dba/sds/sds_nav.sql
-- SYSTEM: ShouTech ERP Enterprise Core
-- MODULE: Navigation Seed Data (Menu + Ribbon) â€” AUTO-GENERATED
-- GENERATOR: tools/generate_nav_seed.ps1
-- GENERATED: 2026-08-13 22:34:03
-- STATS: 17 menus, 17 tabs, 55 groups, 215 items
-- â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•

SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

RAISERROR(N'ðŸŒ± [SEED] Loading enterprise navigation catalog (sys.MainMenuItems / Ribbon*)...', 0, 1) WITH NOWAIT;

BEGIN TRANSACTION;
BEGIN TRY

    -- Navigation permissions catalog
    MERGE INTO sec.Permissions AS Target
    USING (VALUES
        ('PERM_NAV_ACCOUNTS_ACCOUNTBALANCE', 'Accounts', N'رصيد حساب', 'Account Balance'),
        ('PERM_NAV_ACCOUNTS_ACCOUNTCOMPARISON', 'Accounts', N'مقارنة حساب', 'Account Comparison'),
        ('PERM_NAV_ACCOUNTS_ACCOUNTMOVEMENTCHART', 'Accounts', N'مخطط حركة حساب', 'Account Movement Chart'),
        ('PERM_NAV_ACCOUNTS_AGINGRECEIVABLES', 'Accounts', N'أعمار الذمم', 'Aging Receivables'),
        ('PERM_NAV_ACCOUNTS_AVERAGECURRENCYRATE', 'Accounts', N'متوسط سعر العملات', 'Average Currency Rate'),
        ('PERM_NAV_ACCOUNTS_BALANCESHEET', 'Accounts', N'الميزانية', 'Balance Sheet'),
        ('PERM_NAV_ACCOUNTS_BRANCHACCOUNTMOVEMENT', 'Accounts', N'حركة حساب الفروع', 'Branch Account Movement'),
        ('PERM_NAV_ACCOUNTS_CASHFLOWSTATEMENT', 'Accounts', N'قائمة التدفق النقدي', 'Cash Flow Statement'),
        ('PERM_NAV_ACCOUNTS_CHARTOFACCOUNTS', 'Accounts', N'شجرة الحسابات', 'Chart of Accounts'),
        ('PERM_NAV_ACCOUNTS_COLLECTIONRATES', 'Accounts', N'نسب التحصيل', 'Collection Rates'),
        ('PERM_NAV_ACCOUNTS_COSTCENTER', 'Accounts', N'مركز كلفة', 'Cost Center'),
        ('PERM_NAV_ACCOUNTS_COSTCENTERBALANCE', 'Accounts', N'ميزان مركز كلفة', 'Cost Center Balance'),
        ('PERM_NAV_ACCOUNTS_COSTCENTERCARD', 'Accounts', N'بطاقة مركز كلفة', 'Cost Center Card'),
        ('PERM_NAV_ACCOUNTS_COSTCENTERMATERIALMOVEMENT', 'Accounts', N'حركة مواد مركز كلفة', 'Cost Center Material Movement'),
        ('PERM_NAV_ACCOUNTS_COSTCENTERREPORT', 'Accounts', N'تقرير مركز كلفة', 'Cost Center Report'),
        ('PERM_NAV_ACCOUNTS_CURRENCYRATES', 'Accounts', N'نشرة أسعار العملات', 'Currency Exchange Rates'),
        ('PERM_NAV_ACCOUNTS_CUSTOMERSTATEMENT', 'Accounts', N'كشف حساب عميل', 'Customer Statement'),
        ('PERM_NAV_ACCOUNTS_DAILYREPORT', 'Accounts', N'التقرير اليومي', 'Daily Report'),
        ('PERM_NAV_ACCOUNTS_DEFINECURRENCY', 'Accounts', N'تعريف عملة', 'Define Currency'),
        ('PERM_NAV_ACCOUNTS_DORMANTACCOUNTS', 'Accounts', N'الحسابات الراكدة', 'Dormant Accounts'),
        ('PERM_NAV_ACCOUNTS_EXCHANGERATEDIFFERENCES', 'Accounts', N'فروق أسعار الصرف', 'Exchange Rate Differences'),
        ('PERM_NAV_ACCOUNTS_GENERALJOURNAL', 'Accounts', N'دفتر اليومية العامة', 'General Journal'),
        ('PERM_NAV_ACCOUNTS_INCOMESTATEMENT', 'Accounts', N'قائمة الدخل', 'Income Statement'),
        ('PERM_NAV_ACCOUNTS_LEDGER', 'Accounts', N'دفتر الأستاذ', 'General Ledger'),
        ('PERM_NAV_ACCOUNTS_LINKWITHACCOUNTS', 'Accounts', N'ربط مع الحسابات', 'Link with Accounts'),
        ('PERM_NAV_ACCOUNTS_OPERATIONS', 'Accounts', N'التشغيل', 'Operations'),
        ('PERM_NAV_ACCOUNTS_PROFITLOSS', 'Accounts', N'أرباح خسائر', 'Profit & Loss'),
        ('PERM_NAV_ACCOUNTS_TRADING', 'Accounts', N'المتاجرة', 'Trading'),
        ('PERM_NAV_ACCOUNTS_TRIALBALANCE', 'Accounts', N'ميزان المراجعة', 'Trial Balance'),
        ('PERM_NAV_BANKS_BANKBALANCES', 'Banks', N'أرصدة البنوك', 'Bank Balances'),
        ('PERM_NAV_BANKS_BANKESTIMATE', 'Banks', N'كشف البنك التقديري', 'Bank Estimate Statement'),
        ('PERM_NAV_BANKS_BANKRECONCILIATION', 'Banks', N'تسوية بنكية', 'Bank Reconciliation'),
        ('PERM_NAV_BANKS_DEFINEBANKS', 'Banks', N'تعريف البنوك', 'Define Banks'),
        ('PERM_NAV_BONDS_CASHJOURNAL', 'Bonds', N'يومية الصندوق', 'Cash Journal'),
        ('PERM_NAV_BONDS_DEFINEPAYMENTTYPES', 'Bonds', N'تعريف أنماط الدفعات', 'Define Payment Types'),
        ('PERM_NAV_BONDS_DEFINESECURITIES', 'Bonds', N'تعريف الأوراق المالية', 'Define Securities'),
        ('PERM_NAV_BONDS_DEFINEVOUCHERTYPES', 'Bonds', N'تعريف أنماط السندات', 'Define Voucher Types'),
        ('PERM_NAV_BONDS_ENTRYVOUCHER', 'Bonds', N'سند قيد', 'Entry Voucher'),
        ('PERM_NAV_BONDS_INSTALLMENT', 'Bonds', N'تقسيط المبالغ', 'Installment'),
        ('PERM_NAV_BONDS_JOURNALVOUCHER', 'Bonds', N'سند يومية', 'Journal Voucher'),
        ('PERM_NAV_BONDS_MONITORVOUCHERS', 'Bonds', N'مراقبة وتعديل السندات', 'Monitor and Adjust Vouchers'),
        ('PERM_NAV_BONDS_PAYMENTCHEQUE', 'Bonds', N'شيك دفع', 'Payment Cheque'),
        ('PERM_NAV_BONDS_PAYMENTTYPES', 'Bonds', N'أنماط الدفعات', 'Payment Types'),
        ('PERM_NAV_BONDS_PAYMENTVOUCHER', 'Bonds', N'سند دفع', 'Payment Voucher'),
        ('PERM_NAV_BONDS_RECEIPTCHEQUE', 'Bonds', N'شيك قبض', 'Receipt Cheque'),
        ('PERM_NAV_BONDS_RECEIPTVOUCHER', 'Bonds', N'سند قبض', 'Receipt Voucher'),
        ('PERM_NAV_BONDS_SEARCHINSTALLMENT', 'Bonds', N'بحث تقسيط المبالغ', 'Search Installment'),
        ('PERM_NAV_BONDS_SEARCHSECURITIES', 'Bonds', N'بحث الأوراق المالية', 'Search Securities'),
        ('PERM_NAV_CUSTOMERS_AREAS', 'Customers', N'مناطق', 'Areas'),
        ('PERM_NAV_CUSTOMERS_ASSIGNTARGETS', 'Customers', N'تخصيص أهداف العملاء', 'Assign Customer Targets'),
        ('PERM_NAV_CUSTOMERS_BALANCEACCOUNTS', 'Customers', N'ترصيد حسابات العملاء', 'Balance Customer Accounts'),
        ('PERM_NAV_CUSTOMERS_CUSTOMERBALANCE', 'Customers', N'رصيد العملاء', 'Customer Balance'),
        ('PERM_NAV_CUSTOMERS_CUSTOMERCARD', 'Customers', N'بطاقة عميل', 'Customer Card'),
        ('PERM_NAV_CUSTOMERS_CUSTOMERDISCOUNTS', 'Customers', N'حسومات عميل', 'Customer Discounts'),
        ('PERM_NAV_CUSTOMERS_CUSTOMERDUE', 'Customers', N'استحقاق عميل', 'Customer Due'),
        ('PERM_NAV_CUSTOMERS_CUSTOMERGROUPS', 'Customers', N'مجموعات العملاء', 'Customer Groups'),
        ('PERM_NAV_CUSTOMERS_CUSTOMERPRICES', 'Customers', N'أسعار عميل', 'Customer Prices'),
        ('PERM_NAV_CUSTOMERS_CUSTOMERREPORTS', 'Customers', N'تقارير العملاء', 'Customer Reports'),
        ('PERM_NAV_CUSTOMERS_EDITCUSTOMERS', 'Customers', N'تعديل العملاء', 'Edit Customers'),
        ('PERM_NAV_CUSTOMERS_LINKPAYMENTS', 'Customers', N'ربط دفعات العميل', 'Link Customer Payments'),
        ('PERM_NAV_CUSTOMERS_SEARCHCUSTOMERS', 'Customers', N'بحث العملاء', 'Search Customers'),
        ('PERM_NAV_CUSTOMERS_SEARCHDUES', 'Customers', N'بحث الاستحقاقات', 'Search Dues'),
        ('PERM_NAV_CUSTOMERS_TARGETSREPORT', 'Customers', N'تقرير أهداف العملاء', 'Targets Report'),
        ('PERM_NAV_EXIT_EXITANDSHUTDOWN', 'Exit', N'خروج وإطفاء الحاسب', 'Exit and Shutdown Computer'),
        ('PERM_NAV_EXIT_SCREENSAVER', 'Exit', N'شاشة حماية', 'Screen Saver'),
        ('PERM_NAV_EXIT_SWITCHCOMPANY', 'Exit', N'تبديل الشركة', 'Switch Company'),
        ('PERM_NAV_HELP_ABOUT', 'Help', N'حول البرنامج', 'About Program'),
        ('PERM_NAV_HELP_CHECKUPDATES', 'Help', N'تحقق من وجود تحديثات', 'Check for Updates'),
        ('PERM_NAV_HELP_INSTRUCTIONS', 'Help', N'تعليمات البرنامج', 'Program Instructions'),
        ('PERM_NAV_HELP_RENEWLICENSE', 'Help', N'تجديد الترخيص', 'Renew License'),
        ('PERM_NAV_HELP_SUGGESTIONS', 'Help', N'اقتراحاتكم', 'Your Suggestions'),
        ('PERM_NAV_HELP_TECHNICALSUPPORT', 'Help', N'الدعم الفني', 'Technical Support'),
        ('PERM_NAV_HELP_UPDATEFROMFILE', 'Help', N'تحديث من ملف', 'Update from File'),
        ('PERM_NAV_INVENTORY_BRANCHMATERIALS', 'Inventory', N'مواد الفروع', 'Branch Materials'),
        ('PERM_NAV_INVENTORY_CREATEBARCODE', 'Inventory', N'إنشاء باركود', 'Create Barcode'),
        ('PERM_NAV_INVENTORY_CUSTOMERS', 'Inventory', N'تقاطع المواد مع العملاء', 'Material-Customer Intersection'),
        ('PERM_NAV_INVENTORY_DESIGNBARCODE', 'Inventory', N'تصميم وطباعة الباركود', 'Design and Print Barcode'),
        ('PERM_NAV_INVENTORY_EDITMATERIALSPECS', 'Inventory', N'تعديل مواصفات المواد', 'Edit Material Specifications'),
        ('PERM_NAV_INVENTORY_EDITSERIALNUMBER', 'Inventory', N'تعديل رقم تسلسلي', 'Edit Serial Number'),
        ('PERM_NAV_INVENTORY_ENDOFPERIOD', 'Inventory', N'بضاعة آخر المدة', 'End of Period Stock'),
        ('PERM_NAV_INVENTORY_EXPIREDMATERIALS', 'Inventory', N'المواد المنتهية الصلاحية', 'Expired Materials'),
        ('PERM_NAV_INVENTORY_GENERATEBARCODE', 'Inventory', N'توليد الباركود', 'Generate Barcode'),
        ('PERM_NAV_INVENTORY_INVENTORYADJUSTMENT', 'Inventory', N'تسوية جردية', 'Inventory Adjustment'),
        ('PERM_NAV_INVENTORY_INVOICEAGE', 'Inventory', N'أعمار الفواتير', 'Invoice Aging'),
        ('PERM_NAV_INVENTORY_ITEMCARD', 'Inventory', N'بطاقة صنف', 'Item Card'),
        ('PERM_NAV_INVENTORY_MATERIALCARD', 'Inventory', N'بطاقة مادة', 'Material Card'),
        ('PERM_NAV_INVENTORY_MATERIALCOMPARISON', 'Inventory', N'مقارنة مادة', 'Material Comparison'),
        ('PERM_NAV_INVENTORY_MATERIALDISCOUNTS', 'Inventory', N'حسومات المواد', 'Material Discounts'),
        ('PERM_NAV_INVENTORY_MATERIALGROUPMOVEMENTREPORT', 'Inventory', N'تقرير حركة المواد والمجموعات', 'Material and Group Movement Report'),
        ('PERM_NAV_INVENTORY_MATERIALGROUPS', 'Inventory', N'مجموعات المواد', 'Material Groups'),
        ('PERM_NAV_INVENTORY_MATERIALLIST', 'Inventory', N'لائحة المواد', 'Material List'),
        ('PERM_NAV_INVENTORY_MATERIALMOVEMENT', 'Inventory', N'حركة مادة', 'Material Movement'),
        ('PERM_NAV_INVENTORY_MATERIALMOVEMENTCHART', 'Inventory', N'مخطط حركة مادة', 'Material Movement Chart'),
        ('PERM_NAV_INVENTORY_MATERIALPRICEHISTORY', 'Inventory', N'تاريخ أسعار المواد', 'Material Price History'),
        ('PERM_NAV_INVENTORY_MATERIALPROFITS', 'Inventory', N'أرباح المواد', 'Material Profits'),
        ('PERM_NAV_INVENTORY_MATERIALSTATISTICS', 'Inventory', N'إحصائيات المواد', 'Material Statistics'),
        ('PERM_NAV_INVENTORY_MATERIALTREE', 'Inventory', N'شجرة المواد', 'Material Tree'),
        ('PERM_NAV_INVENTORY_MOSTACTIVEMATERIALS', 'Inventory', N'المواد الأكثر حركة', 'Most Active Materials'),
        ('PERM_NAV_INVENTORY_NEGATIVEOUTPUT', 'Inventory', N'الإخراج بالسالب', 'Negative Output'),
        ('PERM_NAV_INVENTORY_PRICELIST', 'Inventory', N'قائمة الأسعار', 'Price List'),
        ('PERM_NAV_INVENTORY_SALESREPORT', 'Inventory', N'تقرير المبيعات', 'Sales Report'),
        ('PERM_NAV_INVENTORY_SEARCHMATERIAL', 'Inventory', N'بحث المواد', 'Search Material'),
        ('PERM_NAV_INVENTORY_SERIALNUMBERSREPORT', 'Inventory', N'تقرير الأرقام التسلسلية', 'Serial Numbers Report'),
        ('PERM_NAV_INVENTORY_SERVICEMATERIALS', 'Inventory', N'تقارير المواد الخدمية', 'Service Materials Reports'),
        ('PERM_NAV_INVENTORY_SHORTAGELIST', 'Inventory', N'لائحة النواقص', 'Shortage List'),
        ('PERM_NAV_INVENTORY_STAGNANTMATERIALS', 'Inventory', N'المواد الراكدة', 'Stagnant Materials'),
        ('PERM_NAV_INVENTORY_TRANSFERMATERIAL', 'Inventory', N'نقل حركة مادة', 'Transfer Material Movement'),
        ('PERM_NAV_INVENTORY_WAREHOUSECARD', 'Inventory', N'بطاقة مستودع', 'Warehouse Card'),
        ('PERM_NAV_INVENTORY_WAREHOUSEINVENTORY', 'Inventory', N'جرد المستودعات', 'Warehouse Inventory'),
        ('PERM_NAV_INVOICES_CASHSALES', 'Invoices', N'فواتير المبيعات النقدية', 'Cash Sales Invoices'),
        ('PERM_NAV_INVOICES_CLOSECASH', 'Invoices', N'إغلاق الصندوق', 'Close Cash'),
        ('PERM_NAV_INVOICES_COMPRESSINVOICES', 'Invoices', N'ضغط الفواتير', 'Compress Invoices'),
        ('PERM_NAV_INVOICES_DEFINEINVOICES', 'Invoices', N'تعريف الفواتير', 'Define Invoices'),
        ('PERM_NAV_INVOICES_INVENTORYCOUNT', 'Invoices', N'فاتورة محضر جرد', 'Inventory Count Invoice'),
        ('PERM_NAV_INVOICES_INVOICEPROFITS', 'Invoices', N'أرباح الفواتير', 'Invoice Profits'),
        ('PERM_NAV_INVOICES_MATERIALENTRY', 'Invoices', N'فاتورة إدخال مواد', 'Material Entry Invoice'),
        ('PERM_NAV_INVOICES_MATERIALEXIT', 'Invoices', N'فاتورة إخراج مواد', 'Material Exit Invoice'),
        ('PERM_NAV_INVOICES_OPENINGSTOCK', 'Invoices', N'فاتورة بضاعة أول المدة', 'Opening Stock Invoice'),
        ('PERM_NAV_INVOICES_PACKINGLIST', 'Invoices', N'لائحة التعبئة', 'Packing List'),
        ('PERM_NAV_INVOICES_PRINTBARCODE', 'Invoices', N'طباعة الباركود', 'Print Barcode'),
        ('PERM_NAV_INVOICES_PURCHASEINVOICE', 'Invoices', N'فاتورة مشتريات', 'Purchase Invoice'),
        ('PERM_NAV_INVOICES_PURCHASERETURN', 'Invoices', N'فاتورة مردودات مشتريات', 'Purchase Return Invoice'),
        ('PERM_NAV_INVOICES_QUOTATION', 'Invoices', N'عرض سعر', 'Quotation'),
        ('PERM_NAV_INVOICES_REPOSTINVOICES', 'Invoices', N'إعادة ترحيل الفواتير', 'Repost Invoices'),
        ('PERM_NAV_INVOICES_SALESINVOICE', 'Invoices', N'فاتورة مبيعات', 'Sales Invoice'),
        ('PERM_NAV_INVOICES_SALESRETURN', 'Invoices', N'فاتورة مردودات مبيعات', 'Sales Return Invoice'),
        ('PERM_NAV_INVOICES_SEARCHINVOICES', 'Invoices', N'بحث الفواتير', 'Search Invoices'),
        ('PERM_NAV_INVOICES_SEARCHQUOTATIONS', 'Invoices', N'بحث عروض السعر', 'Search Quotations'),
        ('PERM_NAV_INVOICES_TRANSFER', 'Invoices', N'مناقلة', 'Transfer'),
        ('PERM_NAV_MANUFACTURING_ADDITIONALCOSTVARIANCE', 'Manufacturing', N'انحراف التكاليف الإضافية', 'Additional Cost Variance'),
        ('PERM_NAV_MANUFACTURING_MANUFACTUREDMATERIALCOSTS', 'Manufacturing', N'تكاليف المواد المصنعة', 'Manufactured Material Costs'),
        ('PERM_NAV_MANUFACTURING_MANUFACTUREDMATERIALCOSTVARIANCE', 'Manufacturing', N'انحراف التكاليف الإضافية للمواد المصنعة', 'Additional Cost Variance for Manufactured Materials'),
        ('PERM_NAV_MANUFACTURING_MANUFACTURINGCOSTVARIANCE', 'Manufacturing', N'انحراف تكاليف المواد المصنعة', 'Manufactured Material Cost Variance'),
        ('PERM_NAV_MANUFACTURING_MANUFACTURINGFEASIBILITY', 'Manufacturing', N'إمكانية التصنيع', 'Manufacturing Feasibility'),
        ('PERM_NAV_MANUFACTURING_MANUFACTURINGMODELS', 'Manufacturing', N'نماذج التصنيع', 'Manufacturing Models'),
        ('PERM_NAV_MANUFACTURING_MANUFACTURINGPROCESS', 'Manufacturing', N'عملية تصنيع', 'Manufacturing Process'),
        ('PERM_NAV_MANUFACTURING_RAWMATERIALCOSTVARIANCE', 'Manufacturing', N'انحراف تكاليف المواد الأولية', 'Raw Material Cost Variance'),
        ('PERM_NAV_MANUFACTURING_REPOSTMANUFACTURING', 'Manufacturing', N'إعادة ترحيل عمليات التصنيع', 'Repost Manufacturing Operations'),
        ('PERM_NAV_MANUFACTURING_SEARCHMANUFACTURING', 'Manufacturing', N'بحث التصنيع', 'Search Manufacturing'),
        ('PERM_NAV_MENU_EXIT', 'Menu', N'خروج', 'Exit'),
        ('PERM_NAV_MENU_EXPORT', 'Menu', N'تصدير بيانات', 'Export Data'),
        ('PERM_NAV_MENU_EXPORTPOS', 'Menu', N'تصدير بيانات نقطة بيع', 'Export POS Data'),
        ('PERM_NAV_MENU_IMPORT', 'Menu', N'استيراد بيانات', 'Import Data'),
        ('PERM_NAV_MENU_IMPORTCARD', 'Menu', N'استيراد بطاقة', 'Import Card'),
        ('PERM_NAV_MENU_IMPORTPOS', 'Menu', N'استيراد بيانات نقطة بيع', 'Import POS Data'),
        ('PERM_NAV_MENU_NEW', 'Menu', N'جديد', 'New'),
        ('PERM_NAV_MENU_OPEN', 'Menu', N'فتح', 'Open'),
        ('PERM_NAV_ORDERS_DEFINEORDERS', 'Orders', N'تعريف الطلبيات', 'Define Orders'),
        ('PERM_NAV_ORDERS_ORDERPAYMENTS', 'Orders', N'دفعات الطلبيات', 'Order Payments'),
        ('PERM_NAV_ORDERS_ORDERRECEIPTDELIVERY', 'Orders', N'فواتير استلام وتسليم الطلبيات', 'Order Receipt and Delivery Invoices'),
        ('PERM_NAV_ORDERS_PURCHASEORDER', 'Orders', N'طلبية شراء', 'Purchase Order'),
        ('PERM_NAV_ORDERS_SALESORDER', 'Orders', N'طلبية بيع', 'Sales Order'),
        ('PERM_NAV_ORDERS_SEARCHORDERS', 'Orders', N'بحث الطلبيات', 'Search Orders'),
        ('PERM_NAV_ORDERS_TRACKORDERS', 'Orders', N'متابعة الطلبيات', 'Track Orders'),
        ('PERM_NAV_OTHERTOOLS_CLOSEDRIVERCASH', 'OtherTools', N'إغلاق صندوق سائق', 'Close Driver Cash'),
        ('PERM_NAV_OTHERTOOLS_CUSTOMFIELDS', 'OtherTools', N'حقول مخصصة', 'Custom Fields'),
        ('PERM_NAV_OTHERTOOLS_DELIVERYPRICES', 'OtherTools', N'أسعار التوصيل', 'Delivery Prices'),
        ('PERM_NAV_OTHERTOOLS_DRIVERCARD', 'OtherTools', N'بطاقة سائق', 'Driver Card'),
        ('PERM_NAV_OTHERTOOLS_MATERIALSPECS', 'OtherTools', N'تعريف مواصفات المواد', 'Define Material Specifications'),
        ('PERM_NAV_OTHERTOOLS_PAYMENTMETHODS', 'OtherTools', N'تعريف طرق الدفع', 'Define Payment Methods'),
        ('PERM_NAV_OTHERTOOLS_PERMISSIONS', 'OtherTools', N'صلاحيات', 'Permissions'),
        ('PERM_NAV_OTHERTOOLS_PERMISSIONTEMPLATES', 'OtherTools', N'قوالب الصلاحيات', 'Permission Templates'),
        ('PERM_NAV_OTHERTOOLS_PICKUPREQUESTS', 'OtherTools', N'طلبات استلام', 'Pickup Requests'),
        ('PERM_NAV_OTHERTOOLS_ROTATION', 'OtherTools', N'التدوير', 'Rotation'),
        ('PERM_NAV_OTHERTOOLS_SEARCHDELIVERY', 'OtherTools', N'بحث التوصيل', 'Search Delivery'),
        ('PERM_NAV_OTHERTOOLS_UNITSOFMEASURE', 'OtherTools', N'تعريف وحدات القياس', 'Define Units of Measure'),
        ('PERM_NAV_POS_ADJUSTPRICE', 'POS', N'تعديل سعر مادة', 'Adjust Material Price'),
        ('PERM_NAV_POS_ADJUSTQUANTITY', 'POS', N'تعديل كمية مادة', 'Adjust Material Quantity'),
        ('PERM_NAV_POS_DEFINEPOS', 'POS', N'تعريف نقاط البيع', 'Define POS'),
        ('PERM_NAV_POS_DELETEMATERIAL', 'POS', N'حذف مادة', 'Delete Material'),
        ('PERM_NAV_POS_POINTS', 'POS', N'النقاط', 'Points'),
        ('PERM_NAV_POS_POSCASHREPORT', 'POS', N'تقرير صندوق نقطة بيع', 'POS Cash Report'),
        ('PERM_NAV_POS_POSDISCOUNTS', 'POS', N'حسومات نقطة بيع', 'POS Discounts'),
        ('PERM_NAV_POS_SYNCPOS', 'POS', N'مزامنة نقاط البيع', 'Sync POS'),
        ('PERM_NAV_REPORTS_CUSTOMEROVERVIEW', 'Reports', N'لمحة عن عميل', 'Customer Overview'),
        ('PERM_NAV_REPORTS_CUSTOMIZEREPORTS', 'Reports', N'تخصيص التقارير', 'Customize Reports'),
        ('PERM_NAV_REPORTS_CUSTOMREPORTS', 'Reports', N'تقارير مخصصة', 'Custom Reports'),
        ('PERM_NAV_REPORTS_MATERIALOVERVIEW', 'Reports', N'لمحة عن مادة', 'Material Overview'),
        ('PERM_NAV_REPORTS_STATISTICS', 'Reports', N'إحصائيات', 'Statistics'),
        ('PERM_NAV_RIBBONGROUPS_ANALYSIS', 'RibbonGroups', N'تحليل مالي محلي', 'تحليل مالي محلي'),
        ('PERM_NAV_RIBBONGROUPS_ANALYSIS_AI', 'RibbonGroups', N'تحليل مالي AI', 'تحليل مالي AI'),
        ('PERM_NAV_RIBBONGROUPS_APPEARANCE', 'RibbonGroups', N'☀️ الوضع النهاري', '☀️ الوضع النهاري'),
        ('PERM_NAV_SALESREP_ASSIGNSALESREPTARGETS', 'SalesRep', N'تخصيص أهداف المندوبين', 'Assign Sales Rep Targets'),
        ('PERM_NAV_SALESREP_DEVICECARDS', 'SalesRep', N'بطاقات الأجهزة الكفية', 'Device Cards'),
        ('PERM_NAV_SALESREP_DEVICEROUTES', 'SalesRep', N'مسارات الأجهزة الكفية', 'Device Routes'),
        ('PERM_NAV_SALESREP_SALESREPCARD', 'SalesRep', N'بطاقة مندوب', 'Sales Rep Card'),
        ('PERM_NAV_SALESREP_SALESREPCOLLECTIONS', 'SalesRep', N'تحصيلات المندوب', 'Sales Rep Collections'),
        ('PERM_NAV_SALESREP_SALESREPGROUPS', 'SalesRep', N'مجموعات المندوب', 'Sales Rep Groups'),
        ('PERM_NAV_SALESREP_SALESREPMOVEMENT', 'SalesRep', N'حركة مندوب', 'Sales Rep Movement'),
        ('PERM_NAV_SALESREP_SALESREPTARGETSREPORT', 'SalesRep', N'تقرير أهداف المندوبين', 'Sales Rep Targets Report'),
        ('PERM_NAV_SHELL_TOGGLETHEME', 'Shell', N'تبديل المظهر', 'Toggle theme'),
        ('PERM_NAV_TOOLS_ACTIVITYLOG', 'Tools', N'مسجل الحركات', 'Activity Log'),
        ('PERM_NAV_TOOLS_ADDONS', 'Tools', N'إضافات البرنامج', 'Program Add-ons'),
        ('PERM_NAV_TOOLS_AI', 'Tools', N'الذكاء الصناعي', 'Artificial Intelligence'),
        ('PERM_NAV_TOOLS_BACKUP', 'Tools', N'النسخ الاحتياطي', 'Backup'),
        ('PERM_NAV_TOOLS_CALCULATOR', 'Tools', N'آلة حاسبة', 'Calculator'),
        ('PERM_NAV_TOOLS_CHANGEPASSWORD', 'Tools', N'تغيير كلمة المرور', 'Change Password'),
        ('PERM_NAV_TOOLS_KEYBOARD', 'Tools', N'لوحة المفاتيح', 'Keyboard'),
        ('PERM_NAV_TOOLS_LANGUAGE', 'Tools', N'🌐 عربي', '🌐 عربي'),
        ('PERM_NAV_TOOLS_LANGUAGE_ENGLISH', 'Tools', N'🌐 English', '🌐 English'),
        ('PERM_NAV_TOOLS_LANGUAGE_FRAN_AIS', 'Tools', N'🌐 Français', '🌐 Français'),
        ('PERM_NAV_TOOLS_LANGUAGE_T_RK_E', 'Tools', N'🌐 Türkçe', '🌐 Türkçe'),
        ('PERM_NAV_TOOLS_MAINTENANCEWIZARD', 'Tools', N'معالج الصيانة', 'Maintenance Wizard'),
        ('PERM_NAV_TOOLS_OPTIONS', 'Tools', N'خيارات', 'Options'),
        ('PERM_NAV_VIEW_COMPANYINFO', 'View', N'معلومات الشركة', 'Company Information'),
        ('PERM_NAV_VIEW_COSTCENTERTREE', 'View', N'شجرة مراكز الكلف', 'Cost Center Tree'),
        ('PERM_NAV_VIEW_EXPORTDATA', 'View', N'تصدير البيانات', 'Export Data'),
        ('PERM_NAV_VIEW_INFOWINDOW', 'View', N'نافذة المعلومات', 'Information Window'),
        ('PERM_NAV_VIEW_MANUFACTURINGTREE', 'View', N'شجرة التصنيع', 'Manufacturing Tree')
    ) AS Source (PermissionCode, ModuleName, PermissionNameAR, PermissionNameEN)
    ON Target.PermissionCode = Source.PermissionCode
    WHEN NOT MATCHED THEN
        INSERT (PermissionCode, ModuleName, PermissionNameAR, PermissionNameEN)
        VALUES (Source.PermissionCode, Source.ModuleName, Source.PermissionNameAR, Source.PermissionNameEN);

    MERGE INTO sys.MainMenuItems AS Target
    USING (VALUES
        (1, 1, 'MMI_FILE', 'TabFile', 'Menu.File', N'📁', 'File', 10),
        (1, 1, 'MMI_INVENTORY', 'TabInventory', 'Menu.Inventory', N'📦', 'Inventory', 20),
        (1, 1, 'MMI_ACCOUNTS', 'TabAccounts', 'Menu.Accounts', N'💰', 'Accounting', 30),
        (1, 1, 'MMI_BONDS', 'TabBonds', 'Menu.Bonds', N'📋', 'Vouchers', 40),
        (1, 1, 'MMI_INVOICES', 'TabInvoices', 'Menu.Invoices', N'🧾', 'Invoices', 50),
        (1, 1, 'MMI_POS', 'TabPOS', 'Menu.POS', N'🛍️', 'PointOfSale', 60),
        (1, 1, 'MMI_ORDERS', 'TabOrders', 'Menu.Orders', N'📋', 'Orders', 70),
        (1, 1, 'MMI_CUSTOMERS', 'TabCustomers', 'Menu.Customers', N'👤', 'Customers', 80),
        (1, 1, 'MMI_SALESREP', 'TabSalesRep', 'Menu.SalesRep', N'🚶', 'SalesRepresentative', 90),
        (1, 1, 'MMI_MANUFACTURING', 'TabManufacturing', 'Menu.Manufacturing', N'🏗️', 'Manufacturing', 100),
        (1, 1, 'MMI_BANKS', 'TabBanks', 'Menu.Banks', N'🏦', 'Banks', 110),
        (1, 1, 'MMI_REPORTS', 'TabReports', 'Menu.Reports', N'📊', 'Reports', 120),
        (1, 1, 'MMI_TOOLS', 'TabTools', 'Menu.Tools', N'🔧', 'Tools', 130),
        (1, 1, 'MMI_OTHERTOOLS', 'TabOtherTools', 'Menu.OtherTools', N'⚙️', 'Administration', 140),
        (1, 1, 'MMI_VIEW', 'TabView', 'Menu.View', N'👁️', 'View', 150),
        (1, 1, 'MMI_EXIT', 'TabExit', 'Menu.Exit', N'🚪', 'Session', 160),
        (1, 1, 'MMI_HELP', 'TabHelp', 'Menu.Help', N'❓', 'Help', 170)
    ) AS Source (TenantID, CompanyID, MenuItemCode, TabCode, LocalizationKey, IconEmoji, ModuleCode, DisplayOrder)
    ON Target.TenantID = Source.TenantID AND Target.CompanyID = Source.CompanyID AND Target.MenuItemCode = Source.MenuItemCode
    WHEN MATCHED THEN UPDATE SET
        TabCode = Source.TabCode,
        LocalizationKey = Source.LocalizationKey,
        IconEmoji = Source.IconEmoji,
        ModuleCode = Source.ModuleCode,
        DisplayOrder = Source.DisplayOrder,
        IsActive = 1,
        IsDeleted = 0,
        UpdatedAt = SYSDATETIME()
    WHEN NOT MATCHED THEN
        INSERT (TenantID, CompanyID, MenuItemCode, TabCode, LocalizationKey, IconEmoji, ModuleCode, DisplayOrder)
        VALUES (Source.TenantID, Source.CompanyID, Source.MenuItemCode, Source.TabCode, Source.LocalizationKey, Source.IconEmoji, Source.ModuleCode, Source.DisplayOrder);

    MERGE INTO sys.RibbonTabs AS Target
    USING (VALUES
        (1, 1, 'TabFile', 'MMI_FILE', 'Menu.File', N'📁', 'File', 10),
        (1, 1, 'TabInventory', 'MMI_INVENTORY', 'Menu.Inventory', N'📦', 'Inventory', 20),
        (1, 1, 'TabAccounts', 'MMI_ACCOUNTS', 'Menu.Accounts', N'💰', 'Accounting', 30),
        (1, 1, 'TabBonds', 'MMI_BONDS', 'Menu.Bonds', N'📋', 'Vouchers', 40),
        (1, 1, 'TabInvoices', 'MMI_INVOICES', 'Menu.Invoices', N'🧾', 'Invoices', 50),
        (1, 1, 'TabPOS', 'MMI_POS', 'Menu.POS', N'🛍', 'PointOfSale', 60),
        (1, 1, 'TabOrders', 'MMI_ORDERS', 'Menu.Orders', N'📋', 'Orders', 70),
        (1, 1, 'TabCustomers', 'MMI_CUSTOMERS', 'Menu.Customers', N'👤', 'Customers', 80),
        (1, 1, 'TabSalesRep', 'MMI_SALESREP', 'Menu.SalesRep', N'🚶', 'SalesRepresentative', 90),
        (1, 1, 'TabManufacturing', 'MMI_MANUFACTURING', 'Menu.Manufacturing', N'🏗', 'Manufacturing', 100),
        (1, 1, 'TabBanks', 'MMI_BANKS', 'Menu.Banks', N'🏦', 'Banks', 110),
        (1, 1, 'TabReports', 'MMI_REPORTS', 'Menu.Reports', N'📊', 'Reports', 120),
        (1, 1, 'TabTools', 'MMI_TOOLS', 'Menu.Tools', N'🔧', 'Tools', 130),
        (1, 1, 'TabOtherTools', 'MMI_OTHERTOOLS', 'Menu.OtherTools', N'⚙️', 'Administration', 140),
        (1, 1, 'TabView', 'MMI_VIEW', 'Menu.View', N'👁', 'View', 150),
        (1, 1, 'TabExit', 'MMI_EXIT', 'Menu.Exit', N'🚪', 'Session', 160),
        (1, 1, 'TabHelp', 'MMI_HELP', 'Menu.Help', N'❓', 'Help', 170)
    ) AS Source (TenantID, CompanyID, TabCode, MenuItemCode, LocalizationKey, HeaderIcon, ModuleCode, DisplayOrder)
    ON Target.TenantID = Source.TenantID AND Target.CompanyID = Source.CompanyID AND Target.TabCode = Source.TabCode
    WHEN MATCHED THEN UPDATE SET
        MenuItemCode = Source.MenuItemCode,
        LocalizationKey = Source.LocalizationKey,
        HeaderIcon = Source.HeaderIcon,
        ModuleCode = Source.ModuleCode,
        DisplayOrder = Source.DisplayOrder,
        IsActive = 1,
        IsDeleted = 0,
        UpdatedAt = SYSDATETIME()
    WHEN NOT MATCHED THEN
        INSERT (TenantID, CompanyID, TabCode, MenuItemCode, LocalizationKey, HeaderIcon, ModuleCode, DisplayOrder)
        VALUES (Source.TenantID, Source.CompanyID, Source.TabCode, Source.MenuItemCode, Source.LocalizationKey, Source.HeaderIcon, Source.ModuleCode, Source.DisplayOrder);

    MERGE INTO sys.RibbonGroups AS Target
    USING (VALUES
        (1, 1, 'TABFILE_RIBBONGROUPS_OPERATIONS', 'TabFile', 'RibbonGroups.Operations', N'العمليات', 'Operations', 10),
        (1, 1, 'TABFILE_RIBBONGROUPS_POS', 'TabFile', 'RibbonGroups.POS', N'نقطة بيع', 'Point of Sale', 20),
        (1, 1, 'TABFILE_MENU_EXIT', 'TabFile', 'Menu.Exit', N'خروج', 'Exit', 30),
        (1, 1, 'TABINVENTORY_RIBBONGROUPS_CARDS', 'TabInventory', 'RibbonGroups.Cards', N'البطاقات', 'Cards', 10),
        (1, 1, 'TABINVENTORY_RIBBONGROUPS_BARCODE', 'TabInventory', 'RibbonGroups.Barcode', N'الباركود', 'Barcode', 20),
        (1, 1, 'TABINVENTORY_RIBBONGROUPS_MOVEMENTS', 'TabInventory', 'RibbonGroups.Movements', N'الحركات', 'Movements', 30),
        (1, 1, 'TABINVENTORY_INVENTORY_MATERIALREPORTS', 'TabInventory', 'Inventory.MaterialReports', N'تقارير المواد', 'Material Reports', 40),
        (1, 1, 'TABINVENTORY_RIBBONGROUPS_OTHER', 'TabInventory', 'RibbonGroups.Other', N'أخرى', 'Other', 50),
        (1, 1, 'TABACCOUNTS_RIBBONGROUPS_GENERAL', 'TabAccounts', 'RibbonGroups.General', N'عام', 'General', 10),
        (1, 1, 'TABACCOUNTS_ACCOUNTS_CURRENCIES', 'TabAccounts', 'Accounts.Currencies', N'العملات', 'Currencies', 20),
        (1, 1, 'TABACCOUNTS_RIBBONGROUPS_REPORTS', 'TabAccounts', 'RibbonGroups.Reports', N'التقارير', 'Reports', 30),
        (1, 1, 'TABACCOUNTS_RIBBONGROUPS_CLOSINGACCOUNTS', 'TabAccounts', 'RibbonGroups.ClosingAccounts', N'الحسابات الختامية', 'Closing Accounts', 40),
        (1, 1, 'TABACCOUNTS_ACCOUNTS_FINANCIALSTATEMENTS', 'TabAccounts', 'Accounts.FinancialStatements', N'القوائم المالية', 'Financial Statements', 50),
        (1, 1, 'TABACCOUNTS_RIBBONGROUPS_ANALYSIS', 'TabAccounts', 'RibbonGroups.Analysis', N'تحليل', 'Analysis', 60),
        (1, 1, 'TABBONDS_BONDS_TITLE', 'TabBonds', 'Bonds.Title', N'السندات', 'Bonds', 10),
        (1, 1, 'TABBONDS_RIBBONGROUPS_INSTALLMENTS', 'TabBonds', 'RibbonGroups.Installments', N'التقسيط', 'Installments', 20),
        (1, 1, 'TABBONDS_RIBBONGROUPS_SECURITIES', 'TabBonds', 'RibbonGroups.Securities', N'الأوراق المالية', 'Securities', 30),
        (1, 1, 'TABBONDS_RIBBONGROUPS_PAYMENTS', 'TabBonds', 'RibbonGroups.Payments', N'الدفعات', 'Payments', 40),
        (1, 1, 'TABBONDS_RIBBONGROUPS_MONITORING', 'TabBonds', 'RibbonGroups.Monitoring', N'مراقبة', 'Monitoring', 50),
        (1, 1, 'TABINVOICES_INVOICES_TITLE', 'TabInvoices', 'Invoices.Title', N'الفواتير', 'Invoices', 10),
        (1, 1, 'TABINVOICES_INVOICES_PURCHASES', 'TabInvoices', 'Invoices.Purchases', N'المشتريات', 'Purchases', 20),
        (1, 1, 'TABINVOICES_INVOICES_SALES', 'TabInvoices', 'Invoices.Sales', N'المبيعات', 'Sales', 30),
        (1, 1, 'TABINVOICES_RIBBONGROUPS_GENERAL', 'TabInvoices', 'RibbonGroups.General', N'عام', 'General', 40),
        (1, 1, 'TABINVOICES_RIBBONGROUPS_OTHERTOOLS', 'TabInvoices', 'RibbonGroups.OtherTools', N'أدوات أخرى', 'Other Tools', 50),
        (1, 1, 'TABPOS_RIBBONGROUPS_MANAGEMENT', 'TabPOS', 'RibbonGroups.Management', N'الإدارة', 'Management', 10),
        (1, 1, 'TABPOS_MENU_REPORTS', 'TabPOS', 'Menu.Reports', N'تقارير', 'Reports', 20),
        (1, 1, 'TABORDERS_RIBBONGROUPS_ORDERS', 'TabOrders', 'RibbonGroups.Orders', N'الطلبيات', 'Orders', 10),
        (1, 1, 'TABORDERS_RIBBONGROUPS_GENERAL', 'TabOrders', 'RibbonGroups.General', N'عام', 'General', 20),
        (1, 1, 'TABCUSTOMERS_RIBBONGROUPS_CARDS', 'TabCustomers', 'RibbonGroups.Cards', N'البطاقات', 'Cards', 10),
        (1, 1, 'TABCUSTOMERS_RIBBONGROUPS_TARGETS', 'TabCustomers', 'RibbonGroups.Targets', N'الأهداف', 'Targets', 20),
        (1, 1, 'TABCUSTOMERS_RIBBONGROUPS_FOLLOWUP', 'TabCustomers', 'RibbonGroups.FollowUp', N'المتابعة', 'Follow Up', 30),
        (1, 1, 'TABCUSTOMERS_RIBBONGROUPS_REPORTS', 'TabCustomers', 'RibbonGroups.Reports', N'التقارير', 'Reports', 40),
        (1, 1, 'TABSALESREP_RIBBONGROUPS_CARDS', 'TabSalesRep', 'RibbonGroups.Cards', N'البطاقات', 'Cards', 10),
        (1, 1, 'TABSALESREP_RIBBONGROUPS_TARGETS', 'TabSalesRep', 'RibbonGroups.Targets', N'الأهداف', 'Targets', 20),
        (1, 1, 'TABSALESREP_RIBBONGROUPS_FOLLOWUP', 'TabSalesRep', 'RibbonGroups.FollowUp', N'المتابعة', 'Follow Up', 30),
        (1, 1, 'TABSALESREP_RIBBONGROUPS_MOBILEDEVICES', 'TabSalesRep', 'RibbonGroups.MobileDevices', N'الأجهزة الكفية', 'Mobile Devices', 40),
        (1, 1, 'TABMANUFACTURING_RIBBONGROUPS_MANAGEMENT', 'TabManufacturing', 'RibbonGroups.Management', N'الإدارة', 'Management', 10),
        (1, 1, 'TABMANUFACTURING_RIBBONGROUPS_COSTVARIANCES', 'TabManufacturing', 'RibbonGroups.CostVariances', N'انحرافات التكاليف', 'Cost Variances', 20),
        (1, 1, 'TABMANUFACTURING_RIBBONGROUPS_REPORTS', 'TabManufacturing', 'RibbonGroups.Reports', N'التقارير', 'Reports', 30),
        (1, 1, 'TABBANKS_RIBBONGROUPS_MANAGEMENT', 'TabBanks', 'RibbonGroups.Management', N'الإدارة', 'Management', 10),
        (1, 1, 'TABREPORTS_RIBBONGROUPS_REPORTS', 'TabReports', 'RibbonGroups.Reports', N'التقارير', 'Reports', 10),
        (1, 1, 'TABTOOLS_RIBBONGROUPS_TOOLS', 'TabTools', 'RibbonGroups.Tools', N'الأدوات', 'Tools', 10),
        (1, 1, 'TABTOOLS_TOOLS_LANGUAGE', 'TabTools', 'Tools.Language', N'اللغة', 'Language', 20),
        (1, 1, 'TABTOOLS_RIBBONGROUPS_SECURITY', 'TabTools', 'RibbonGroups.Security', N'الأمان', 'Security', 30),
        (1, 1, 'TABTOOLS_RIBBONGROUPS_ADVANCED', 'TabTools', 'RibbonGroups.Advanced', N'متقدم', 'Advanced', 40),
        (1, 1, 'TABOTHERTOOLS_RIBBONGROUPS_MANAGEMENT', 'TabOtherTools', 'RibbonGroups.Management', N'الإدارة', 'Management', 10),
        (1, 1, 'TABOTHERTOOLS_RIBBONGROUPS_DEFINITIONS', 'TabOtherTools', 'RibbonGroups.Definitions', N'التعريفات', 'Definitions', 20),
        (1, 1, 'TABOTHERTOOLS_RIBBONGROUPS_DELIVERY', 'TabOtherTools', 'RibbonGroups.Delivery', N'التوصيل', 'Delivery', 30),
        (1, 1, 'TABVIEW_RIBBONGROUPS_APPEARANCE', 'TabView', 'RibbonGroups.Appearance', N'المظهر', 'Appearance', 10),
        (1, 1, 'TABVIEW_RIBBONGROUPS_TREES', 'TabView', 'RibbonGroups.Trees', N'الأشجار', 'Trees', 20),
        (1, 1, 'TABVIEW_RIBBONGROUPS_INFORMATION', 'TabView', 'RibbonGroups.Information', N'المعلومات', 'Information', 30),
        (1, 1, 'TABEXIT_RIBBONGROUPS_EXITALT', 'TabExit', 'RibbonGroups.ExitAlt', N'الخروج', 'Exit', 10),
        (1, 1, 'TABHELP_RIBBONGROUPS_UPDATES', 'TabHelp', 'RibbonGroups.Updates', N'التحديثات', 'Updates', 10),
        (1, 1, 'TABHELP_RIBBONGROUPS_SUPPORT', 'TabHelp', 'RibbonGroups.Support', N'الدعم', 'Support', 20),
        (1, 1, 'TABHELP_RIBBONGROUPS_LICENSING', 'TabHelp', 'RibbonGroups.Licensing', N'الترخيص', 'Licensing', 30)
    ) AS Source (TenantID, CompanyID, GroupCode, TabCode, LocalizationKey, TitleAR, TitleEN, DisplayOrder)
    ON Target.TenantID = Source.TenantID AND Target.CompanyID = Source.CompanyID AND Target.GroupCode = Source.GroupCode
    WHEN MATCHED THEN UPDATE SET
        TabCode = Source.TabCode,
        LocalizationKey = Source.LocalizationKey,
        TitleAR = Source.TitleAR,
        TitleEN = Source.TitleEN,
        DisplayOrder = Source.DisplayOrder,
        IsActive = 1,
        IsDeleted = 0,
        UpdatedAt = SYSDATETIME()
    WHEN NOT MATCHED THEN
        INSERT (TenantID, CompanyID, GroupCode, TabCode, LocalizationKey, TitleAR, TitleEN, DisplayOrder)
        VALUES (Source.TenantID, Source.CompanyID, Source.GroupCode, Source.TabCode, Source.LocalizationKey, Source.TitleAR, Source.TitleEN, Source.DisplayOrder);

    MERGE INTO sys.RibbonItems AS Target
    USING (VALUES
        (1, 1, 'TABFILE_RIBBONGROUPS_OPERATIONS_MENU_NEW', 'TABFILE_RIBBONGROUPS_OPERATIONS', 'TabFile', 'Menu.New', 'Menu.New', N'جديد', 'New', 'RibbonButton', 'PERM_NAV_MENU_NEW', 10),
        (1, 1, 'TABFILE_RIBBONGROUPS_OPERATIONS_MENU_OPEN', 'TABFILE_RIBBONGROUPS_OPERATIONS', 'TabFile', 'Menu.Open', 'Menu.Open', N'فتح', 'Open', 'RibbonButton', 'PERM_NAV_MENU_OPEN', 20),
        (1, 1, 'TABFILE_RIBBONGROUPS_OPERATIONS_MENU_IMPORT', 'TABFILE_RIBBONGROUPS_OPERATIONS', 'TabFile', 'Menu.Import', 'Menu.Import', N'استيراد بيانات', 'Import Data', 'RibbonButton', 'PERM_NAV_MENU_IMPORT', 30),
        (1, 1, 'TABFILE_RIBBONGROUPS_OPERATIONS_MENU_EXPORT', 'TABFILE_RIBBONGROUPS_OPERATIONS', 'TabFile', 'Menu.Export', 'Menu.Export', N'تصدير بيانات', 'Export Data', 'RibbonButton', 'PERM_NAV_MENU_EXPORT', 40),
        (1, 1, 'TABFILE_RIBBONGROUPS_POS_MENU_IMPORTPOS', 'TABFILE_RIBBONGROUPS_POS', 'TabFile', 'Menu.ImportPOS', 'Menu.ImportPOS', N'استيراد بيانات نقطة بيع', 'Import POS Data', 'RibbonButton', 'PERM_NAV_MENU_IMPORTPOS', 10),
        (1, 1, 'TABFILE_RIBBONGROUPS_POS_MENU_EXPORTPOS', 'TABFILE_RIBBONGROUPS_POS', 'TabFile', 'Menu.ExportPOS', 'Menu.ExportPOS', N'تصدير بيانات نقطة بيع', 'Export POS Data', 'RibbonButton', 'PERM_NAV_MENU_EXPORTPOS', 20),
        (1, 1, 'TABFILE_RIBBONGROUPS_POS_MENU_IMPORTCARD', 'TABFILE_RIBBONGROUPS_POS', 'TabFile', 'Menu.ImportCard', 'Menu.ImportCard', N'استيراد بطاقة', 'Import Card', 'RibbonButton', 'PERM_NAV_MENU_IMPORTCARD', 30),
        (1, 1, 'TABFILE_MENU_EXIT_MENU_EXIT', 'TABFILE_MENU_EXIT', 'TabFile', 'Menu.Exit', 'Menu.Exit', N'خروج', 'Exit', 'RibbonButton', 'PERM_NAV_MENU_EXIT', 10),
        (1, 1, 'TABINVENTORY_RIBBONGROUPS_CARDS_INVENTORY_MATERIALCARD', 'TABINVENTORY_RIBBONGROUPS_CARDS', 'TabInventory', 'Inventory.MaterialCard', 'Inventory.MaterialCard', N'بطاقة مادة', 'Material Card', 'RibbonButton', 'PERM_NAV_INVENTORY_MATERIALCARD', 10),
        (1, 1, 'TABINVENTORY_RIBBONGROUPS_CARDS_INVENTORY_ITEMCARD', 'TABINVENTORY_RIBBONGROUPS_CARDS', 'TabInventory', 'Inventory.ItemCard', 'Inventory.ItemCard', N'بطاقة صنف', 'Item Card', 'RibbonButton', 'PERM_NAV_INVENTORY_ITEMCARD', 20),
        (1, 1, 'TABINVENTORY_RIBBONGROUPS_CARDS_INVENTORY_WAREHOUSECARD', 'TABINVENTORY_RIBBONGROUPS_CARDS', 'TabInventory', 'Inventory.WarehouseCard', 'Inventory.WarehouseCard', N'بطاقة مستودع', 'Warehouse Card', 'RibbonButton', 'PERM_NAV_INVENTORY_WAREHOUSECARD', 30),
        (1, 1, 'TABINVENTORY_RIBBONGROUPS_CARDS_INVENTORY_MATERIALGROUPS', 'TABINVENTORY_RIBBONGROUPS_CARDS', 'TabInventory', 'Inventory.MaterialGroups', 'Inventory.MaterialGroups', N'مجموعات المواد', 'Material Groups', 'RibbonButton', 'PERM_NAV_INVENTORY_MATERIALGROUPS', 40),
        (1, 1, 'TABINVENTORY_RIBBONGROUPS_BARCODE_INVENTORY_GENERATEBARCODE', 'TABINVENTORY_RIBBONGROUPS_BARCODE', 'TabInventory', 'Inventory.GenerateBarcode', 'Inventory.GenerateBarcode', N'توليد الباركود', 'Generate Barcode', 'RibbonButton', 'PERM_NAV_INVENTORY_GENERATEBARCODE', 10),
        (1, 1, 'TABINVENTORY_RIBBONGROUPS_BARCODE_INVENTORY_DESIGNBARCODE', 'TABINVENTORY_RIBBONGROUPS_BARCODE', 'TabInventory', 'Inventory.DesignBarcode', 'Inventory.DesignBarcode', N'تصميم وطباعة الباركود', 'Design and Print Barcode', 'RibbonButton', 'PERM_NAV_INVENTORY_DESIGNBARCODE', 20),
        (1, 1, 'TABINVENTORY_RIBBONGROUPS_BARCODE_INVENTORY_CREATEBARCODE', 'TABINVENTORY_RIBBONGROUPS_BARCODE', 'TabInventory', 'Inventory.CreateBarcode', 'Inventory.CreateBarcode', N'إنشاء باركود', 'Create Barcode', 'RibbonButton', 'PERM_NAV_INVENTORY_CREATEBARCODE', 30),
        (1, 1, 'TABINVENTORY_RIBBONGROUPS_MOVEMENTS_INVENTORY_PRICELIST', 'TABINVENTORY_RIBBONGROUPS_MOVEMENTS', 'TabInventory', 'Inventory.PriceList', 'Inventory.PriceList', N'قائمة الأسعار', 'Price List', 'RibbonButton', 'PERM_NAV_INVENTORY_PRICELIST', 10),
        (1, 1, 'TABINVENTORY_RIBBONGROUPS_MOVEMENTS_INVENTORY_ENDOFPERIOD', 'TABINVENTORY_RIBBONGROUPS_MOVEMENTS', 'TabInventory', 'Inventory.EndOfPeriod', 'Inventory.EndOfPeriod', N'بضاعة آخر المدة', 'End of Period Stock', 'RibbonButton', 'PERM_NAV_INVENTORY_ENDOFPERIOD', 20),
        (1, 1, 'TABINVENTORY_RIBBONGROUPS_MOVEMENTS_INVENTORY_SHORTAGELIST', 'TABINVENTORY_RIBBONGROUPS_MOVEMENTS', 'TabInventory', 'Inventory.ShortageList', 'Inventory.ShortageList', N'لائحة النواقص', 'Shortage List', 'RibbonButton', 'PERM_NAV_INVENTORY_SHORTAGELIST', 30),
        (1, 1, 'TABINVENTORY_RIBBONGROUPS_MOVEMENTS_INVENTORY_TRANSFERMATERIAL', 'TABINVENTORY_RIBBONGROUPS_MOVEMENTS', 'TabInventory', 'Inventory.TransferMaterial', 'Inventory.TransferMaterial', N'نقل حركة مادة', 'Transfer Material Movement', 'RibbonButton', 'PERM_NAV_INVENTORY_TRANSFERMATERIAL', 40),
        (1, 1, 'TABINVENTORY_RIBBONGROUPS_MOVEMENTS_INVENTORY_INVENTORYADJUSTMENT', 'TABINVENTORY_RIBBONGROUPS_MOVEMENTS', 'TabInventory', 'Inventory.InventoryAdjustment', 'Inventory.InventoryAdjustment', N'تسوية جردية', 'Inventory Adjustment', 'RibbonButton', 'PERM_NAV_INVENTORY_INVENTORYADJUSTMENT', 50),
        (1, 1, 'TABINVENTORY_INVENTORY_MATERIALREPORTS_INVENTORY_MATERIALTREE', 'TABINVENTORY_INVENTORY_MATERIALREPORTS', 'TabInventory', 'Inventory.MaterialTree', 'Inventory.MaterialTree', N'شجرة المواد', 'Material Tree', 'RibbonButton', 'PERM_NAV_INVENTORY_MATERIALTREE', 10),
        (1, 1, 'TABINVENTORY_INVENTORY_MATERIALREPORTS_INVENTORY_SEARCHMATERIAL', 'TABINVENTORY_INVENTORY_MATERIALREPORTS', 'TabInventory', 'Inventory.SearchMaterial', 'Inventory.SearchMaterial', N'بحث المواد', 'Search Material', 'RibbonButton', 'PERM_NAV_INVENTORY_SEARCHMATERIAL', 20),
        (1, 1, 'TABINVENTORY_INVENTORY_MATERIALREPORTS_INVENTORY_WAREHOUSEINVENTORY', 'TABINVENTORY_INVENTORY_MATERIALREPORTS', 'TabInventory', 'Inventory.WarehouseInventory', 'Inventory.WarehouseInventory', N'جرد المستودعات', 'Warehouse Inventory', 'RibbonButton', 'PERM_NAV_INVENTORY_WAREHOUSEINVENTORY', 30),
        (1, 1, 'TABINVENTORY_INVENTORY_MATERIALREPORTS_INVENTORY_MATERIALMOVEMENT', 'TABINVENTORY_INVENTORY_MATERIALREPORTS', 'TabInventory', 'Inventory.MaterialMovement', 'Inventory.MaterialMovement', N'حركة مادة', 'Material Movement', 'RibbonButton', 'PERM_NAV_INVENTORY_MATERIALMOVEMENT', 40),
        (1, 1, 'TABINVENTORY_INVENTORY_MATERIALREPORTS_INVENTORY_MATERIALMOVEMENTCHART', 'TABINVENTORY_INVENTORY_MATERIALREPORTS', 'TabInventory', 'Inventory.MaterialMovementChart', 'Inventory.MaterialMovementChart', N'مخطط حركة مادة', 'Material Movement Chart', 'RibbonButton', 'PERM_NAV_INVENTORY_MATERIALMOVEMENTCHART', 50),
        (1, 1, 'TABINVENTORY_INVENTORY_MATERIALREPORTS_INVENTORY_EXPIREDMATERIALS', 'TABINVENTORY_INVENTORY_MATERIALREPORTS', 'TabInventory', 'Inventory.ExpiredMaterials', 'Inventory.ExpiredMaterials', N'المواد المنتهية الصلاحية', 'Expired Materials', 'RibbonButton', 'PERM_NAV_INVENTORY_EXPIREDMATERIALS', 60),
        (1, 1, 'TABINVENTORY_INVENTORY_MATERIALREPORTS_INVENTORY_INVOICEAGE', 'TABINVENTORY_INVENTORY_MATERIALREPORTS', 'TabInventory', 'Inventory.InvoiceAge', 'Inventory.InvoiceAge', N'أعمار الفواتير', 'Invoice Aging', 'RibbonButton', 'PERM_NAV_INVENTORY_INVOICEAGE', 70),
        (1, 1, 'TABINVENTORY_INVENTORY_MATERIALREPORTS_INVENTORY_MATERIALPROFITS', 'TABINVENTORY_INVENTORY_MATERIALREPORTS', 'TabInventory', 'Inventory.MaterialProfits', 'Inventory.MaterialProfits', N'أرباح المواد', 'Material Profits', 'RibbonButton', 'PERM_NAV_INVENTORY_MATERIALPROFITS', 80),
        (1, 1, 'TABINVENTORY_INVENTORY_MATERIALREPORTS_INVENTORY_MATERIALPRICEHISTORY', 'TABINVENTORY_INVENTORY_MATERIALREPORTS', 'TabInventory', 'Inventory.MaterialPriceHistory', 'Inventory.MaterialPriceHistory', N'تاريخ أسعار المواد', 'Material Price History', 'RibbonButton', 'PERM_NAV_INVENTORY_MATERIALPRICEHISTORY', 90),
        (1, 1, 'TABINVENTORY_INVENTORY_MATERIALREPORTS_INVENTORY_SERVICEMATERIALS', 'TABINVENTORY_INVENTORY_MATERIALREPORTS', 'TabInventory', 'Inventory.ServiceMaterials', 'Inventory.ServiceMaterials', N'تقارير المواد الخدمية', 'Service Materials Reports', 'RibbonButton', 'PERM_NAV_INVENTORY_SERVICEMATERIALS', 100),
        (1, 1, 'TABINVENTORY_INVENTORY_MATERIALREPORTS_INVENTORY_MATERIALSTATISTICS', 'TABINVENTORY_INVENTORY_MATERIALREPORTS', 'TabInventory', 'Inventory.MaterialStatistics', 'Inventory.MaterialStatistics', N'إحصائيات المواد', 'Material Statistics', 'RibbonButton', 'PERM_NAV_INVENTORY_MATERIALSTATISTICS', 110),
        (1, 1, 'TABINVENTORY_INVENTORY_MATERIALREPORTS_INVENTORY_STAGNANTMATERIALS', 'TABINVENTORY_INVENTORY_MATERIALREPORTS', 'TabInventory', 'Inventory.StagnantMaterials', 'Inventory.StagnantMaterials', N'المواد الراكدة', 'Stagnant Materials', 'RibbonButton', 'PERM_NAV_INVENTORY_STAGNANTMATERIALS', 120),
        (1, 1, 'TABINVENTORY_INVENTORY_MATERIALREPORTS_INVENTORY_MOSTACTIVEMATERIALS', 'TABINVENTORY_INVENTORY_MATERIALREPORTS', 'TabInventory', 'Inventory.MostActiveMaterials', 'Inventory.MostActiveMaterials', N'المواد الأكثر حركة', 'Most Active Materials', 'RibbonButton', 'PERM_NAV_INVENTORY_MOSTACTIVEMATERIALS', 130),
        (1, 1, 'TABINVENTORY_INVENTORY_MATERIALREPORTS_INVENTORY_MATERIALCOMPARISON', 'TABINVENTORY_INVENTORY_MATERIALREPORTS', 'TabInventory', 'Inventory.MaterialComparison', 'Inventory.MaterialComparison', N'مقارنة مادة', 'Material Comparison', 'RibbonButton', 'PERM_NAV_INVENTORY_MATERIALCOMPARISON', 140),
        (1, 1, 'TABINVENTORY_INVENTORY_MATERIALREPORTS_INVENTORY_MATERIALLIST', 'TABINVENTORY_INVENTORY_MATERIALREPORTS', 'TabInventory', 'Inventory.MaterialList', 'Inventory.MaterialList', N'لائحة المواد', 'Material List', 'RibbonButton', 'PERM_NAV_INVENTORY_MATERIALLIST', 150),
        (1, 1, 'TABINVENTORY_INVENTORY_MATERIALREPORTS_INVENTORY_MATERIALGROUPMOVEMENTREPORT', 'TABINVENTORY_INVENTORY_MATERIALREPORTS', 'TabInventory', 'Inventory.MaterialGroupMovementReport', 'Inventory.MaterialGroupMovementReport', N'تقرير حركة المواد والمجموعات', 'Material and Group Movement Report', 'RibbonButton', 'PERM_NAV_INVENTORY_MATERIALGROUPMOVEMENTREPORT', 160),
        (1, 1, 'TABINVENTORY_INVENTORY_MATERIALREPORTS_INVENTORY_NEGATIVEOUTPUT', 'TABINVENTORY_INVENTORY_MATERIALREPORTS', 'TabInventory', 'Inventory.NegativeOutput', 'Inventory.NegativeOutput', N'الإخراج بالسالب', 'Negative Output', 'RibbonButton', 'PERM_NAV_INVENTORY_NEGATIVEOUTPUT', 170),
        (1, 1, 'TABINVENTORY_RIBBONGROUPS_OTHER_INVENTORY_CUSTOMERS', 'TABINVENTORY_RIBBONGROUPS_OTHER', 'TabInventory', 'Inventory.Customers', 'Inventory.Customers', N'تقاطع المواد مع العملاء', 'Material-Customer Intersection', 'RibbonButton', 'PERM_NAV_INVENTORY_CUSTOMERS', 10),
        (1, 1, 'TABINVENTORY_RIBBONGROUPS_OTHER_INVENTORY_SERIALNUMBERSREPORT', 'TABINVENTORY_RIBBONGROUPS_OTHER', 'TabInventory', 'Inventory.SerialNumbersReport', 'Inventory.SerialNumbersReport', N'تقرير الأرقام التسلسلية', 'Serial Numbers Report', 'RibbonButton', 'PERM_NAV_INVENTORY_SERIALNUMBERSREPORT', 20),
        (1, 1, 'TABINVENTORY_RIBBONGROUPS_OTHER_INVENTORY_EDITSERIALNUMBER', 'TABINVENTORY_RIBBONGROUPS_OTHER', 'TabInventory', 'Inventory.EditSerialNumber', 'Inventory.EditSerialNumber', N'تعديل رقم تسلسلي', 'Edit Serial Number', 'RibbonButton', 'PERM_NAV_INVENTORY_EDITSERIALNUMBER', 30),
        (1, 1, 'TABINVENTORY_RIBBONGROUPS_OTHER_INVENTORY_BRANCHMATERIALS', 'TABINVENTORY_RIBBONGROUPS_OTHER', 'TabInventory', 'Inventory.BranchMaterials', 'Inventory.BranchMaterials', N'مواد الفروع', 'Branch Materials', 'RibbonButton', 'PERM_NAV_INVENTORY_BRANCHMATERIALS', 40),
        (1, 1, 'TABINVENTORY_RIBBONGROUPS_OTHER_INVENTORY_SALESREPORT', 'TABINVENTORY_RIBBONGROUPS_OTHER', 'TabInventory', 'Inventory.SalesReport', 'Inventory.SalesReport', N'تقرير المبيعات', 'Sales Report', 'RibbonButton', 'PERM_NAV_INVENTORY_SALESREPORT', 50),
        (1, 1, 'TABINVENTORY_RIBBONGROUPS_OTHER_INVENTORY_EDITMATERIALSPECS', 'TABINVENTORY_RIBBONGROUPS_OTHER', 'TabInventory', 'Inventory.EditMaterialSpecs', 'Inventory.EditMaterialSpecs', N'تعديل مواصفات المواد', 'Edit Material Specifications', 'RibbonButton', 'PERM_NAV_INVENTORY_EDITMATERIALSPECS', 60),
        (1, 1, 'TABINVENTORY_RIBBONGROUPS_OTHER_INVENTORY_MATERIALDISCOUNTS', 'TABINVENTORY_RIBBONGROUPS_OTHER', 'TabInventory', 'Inventory.MaterialDiscounts', 'Inventory.MaterialDiscounts', N'حسومات المواد', 'Material Discounts', 'RibbonButton', 'PERM_NAV_INVENTORY_MATERIALDISCOUNTS', 70),
        (1, 1, 'TABACCOUNTS_RIBBONGROUPS_GENERAL_ACCOUNTS_CHARTOFACCOUNTS', 'TABACCOUNTS_RIBBONGROUPS_GENERAL', 'TabAccounts', 'Accounts.ChartOfAccounts', 'Accounts.ChartOfAccounts', N'شجرة الحسابات', 'Chart of Accounts', 'RibbonButton', 'PERM_NAV_ACCOUNTS_CHARTOFACCOUNTS', 10),
        (1, 1, 'TABACCOUNTS_RIBBONGROUPS_GENERAL_ACCOUNTS_COSTCENTER', 'TABACCOUNTS_RIBBONGROUPS_GENERAL', 'TabAccounts', 'Accounts.CostCenter', 'Accounts.CostCenter', N'مركز كلفة', 'Cost Center', 'RibbonButton', 'PERM_NAV_ACCOUNTS_COSTCENTER', 20),
        (1, 1, 'TABACCOUNTS_RIBBONGROUPS_GENERAL_ACCOUNTS_COSTCENTERCARD', 'TABACCOUNTS_RIBBONGROUPS_GENERAL', 'TabAccounts', 'Accounts.CostCenterCard', 'Accounts.CostCenterCard', N'بطاقة مركز كلفة', 'Cost Center Card', 'RibbonButton', 'PERM_NAV_ACCOUNTS_COSTCENTERCARD', 30),
        (1, 1, 'TABACCOUNTS_RIBBONGROUPS_GENERAL_ACCOUNTS_LINKWITHACCOUNTS', 'TABACCOUNTS_RIBBONGROUPS_GENERAL', 'TabAccounts', 'Accounts.LinkWithAccounts', 'Accounts.LinkWithAccounts', N'ربط مع الحسابات', 'Link with Accounts', 'RibbonButton', 'PERM_NAV_ACCOUNTS_LINKWITHACCOUNTS', 40),
        (1, 1, 'TABACCOUNTS_RIBBONGROUPS_GENERAL_ACCOUNTS_COSTCENTERREPORT', 'TABACCOUNTS_RIBBONGROUPS_GENERAL', 'TabAccounts', 'Accounts.CostCenterReport', 'Accounts.CostCenterReport', N'تقرير مركز كلفة', 'Cost Center Report', 'RibbonButton', 'PERM_NAV_ACCOUNTS_COSTCENTERREPORT', 50),
        (1, 1, 'TABACCOUNTS_RIBBONGROUPS_GENERAL_ACCOUNTS_COSTCENTERMATERIALMOVEMENT', 'TABACCOUNTS_RIBBONGROUPS_GENERAL', 'TabAccounts', 'Accounts.CostCenterMaterialMovement', 'Accounts.CostCenterMaterialMovement', N'حركة مواد مركز كلفة', 'Cost Center Material Movement', 'RibbonButton', 'PERM_NAV_ACCOUNTS_COSTCENTERMATERIALMOVEMENT', 60),
        (1, 1, 'TABACCOUNTS_RIBBONGROUPS_GENERAL_ACCOUNTS_COSTCENTERBALANCE', 'TABACCOUNTS_RIBBONGROUPS_GENERAL', 'TabAccounts', 'Accounts.CostCenterBalance', 'Accounts.CostCenterBalance', N'ميزان مركز كلفة', 'Cost Center Balance', 'RibbonButton', 'PERM_NAV_ACCOUNTS_COSTCENTERBALANCE', 70),
        (1, 1, 'TABACCOUNTS_ACCOUNTS_CURRENCIES_ACCOUNTS_DEFINECURRENCY', 'TABACCOUNTS_ACCOUNTS_CURRENCIES', 'TabAccounts', 'Accounts.DefineCurrency', 'Accounts.DefineCurrency', N'تعريف عملة', 'Define Currency', 'RibbonButton', 'PERM_NAV_ACCOUNTS_DEFINECURRENCY', 10),
        (1, 1, 'TABACCOUNTS_ACCOUNTS_CURRENCIES_ACCOUNTS_CURRENCYRATES', 'TABACCOUNTS_ACCOUNTS_CURRENCIES', 'TabAccounts', 'Accounts.CurrencyRates', 'Accounts.CurrencyRates', N'نشرة أسعار العملات', 'Currency Exchange Rates', 'RibbonButton', 'PERM_NAV_ACCOUNTS_CURRENCYRATES', 20),
        (1, 1, 'TABACCOUNTS_ACCOUNTS_CURRENCIES_ACCOUNTS_AVERAGECURRENCYRATE', 'TABACCOUNTS_ACCOUNTS_CURRENCIES', 'TabAccounts', 'Accounts.AverageCurrencyRate', 'Accounts.AverageCurrencyRate', N'متوسط سعر العملات', 'Average Currency Rate', 'RibbonButton', 'PERM_NAV_ACCOUNTS_AVERAGECURRENCYRATE', 30),
        (1, 1, 'TABACCOUNTS_ACCOUNTS_CURRENCIES_ACCOUNTS_EXCHANGERATEDIFFERENCES', 'TABACCOUNTS_ACCOUNTS_CURRENCIES', 'TabAccounts', 'Accounts.ExchangeRateDifferences', 'Accounts.ExchangeRateDifferences', N'فروق أسعار الصرف', 'Exchange Rate Differences', 'RibbonButton', 'PERM_NAV_ACCOUNTS_EXCHANGERATEDIFFERENCES', 40),
        (1, 1, 'TABACCOUNTS_RIBBONGROUPS_REPORTS_ACCOUNTS_LEDGER', 'TABACCOUNTS_RIBBONGROUPS_REPORTS', 'TabAccounts', 'Accounts.Ledger', 'Accounts.Ledger', N'دفتر الأستاذ', 'General Ledger', 'RibbonButton', 'PERM_NAV_ACCOUNTS_LEDGER', 10),
        (1, 1, 'TABACCOUNTS_RIBBONGROUPS_REPORTS_ACCOUNTS_CUSTOMERSTATEMENT', 'TABACCOUNTS_RIBBONGROUPS_REPORTS', 'TabAccounts', 'Accounts.CustomerStatement', 'Accounts.CustomerStatement', N'كشف حساب عميل', 'Customer Statement', 'RibbonButton', 'PERM_NAV_ACCOUNTS_CUSTOMERSTATEMENT', 20),
        (1, 1, 'TABACCOUNTS_RIBBONGROUPS_REPORTS_ACCOUNTS_GENERALJOURNAL', 'TABACCOUNTS_RIBBONGROUPS_REPORTS', 'TabAccounts', 'Accounts.GeneralJournal', 'Accounts.GeneralJournal', N'دفتر اليومية العامة', 'General Journal', 'RibbonButton', 'PERM_NAV_ACCOUNTS_GENERALJOURNAL', 30),
        (1, 1, 'TABACCOUNTS_RIBBONGROUPS_REPORTS_ACCOUNTS_DAILYREPORT', 'TABACCOUNTS_RIBBONGROUPS_REPORTS', 'TabAccounts', 'Accounts.DailyReport', 'Accounts.DailyReport', N'التقرير اليومي', 'Daily Report', 'RibbonButton', 'PERM_NAV_ACCOUNTS_DAILYREPORT', 40),
        (1, 1, 'TABACCOUNTS_RIBBONGROUPS_REPORTS_ACCOUNTS_ACCOUNTMOVEMENTCHART', 'TABACCOUNTS_RIBBONGROUPS_REPORTS', 'TabAccounts', 'Accounts.AccountMovementChart', 'Accounts.AccountMovementChart', N'مخطط حركة حساب', 'Account Movement Chart', 'RibbonButton', 'PERM_NAV_ACCOUNTS_ACCOUNTMOVEMENTCHART', 50),
        (1, 1, 'TABACCOUNTS_RIBBONGROUPS_REPORTS_ACCOUNTS_ACCOUNTBALANCE', 'TABACCOUNTS_RIBBONGROUPS_REPORTS', 'TabAccounts', 'Accounts.AccountBalance', 'Accounts.AccountBalance', N'رصيد حساب', 'Account Balance', 'RibbonButton', 'PERM_NAV_ACCOUNTS_ACCOUNTBALANCE', 60),
        (1, 1, 'TABACCOUNTS_RIBBONGROUPS_REPORTS_ACCOUNTS_BRANCHACCOUNTMOVEMENT', 'TABACCOUNTS_RIBBONGROUPS_REPORTS', 'TabAccounts', 'Accounts.BranchAccountMovement', 'Accounts.BranchAccountMovement', N'حركة حساب الفروع', 'Branch Account Movement', 'RibbonButton', 'PERM_NAV_ACCOUNTS_BRANCHACCOUNTMOVEMENT', 70),
        (1, 1, 'TABACCOUNTS_RIBBONGROUPS_REPORTS_ACCOUNTS_TRIALBALANCE', 'TABACCOUNTS_RIBBONGROUPS_REPORTS', 'TabAccounts', 'Accounts.TrialBalance', 'Accounts.TrialBalance', N'ميزان المراجعة', 'Trial Balance', 'RibbonButton', 'PERM_NAV_ACCOUNTS_TRIALBALANCE', 80),
        (1, 1, 'TABACCOUNTS_RIBBONGROUPS_CLOSINGACCOUNTS_ACCOUNTS_OPERATIONS', 'TABACCOUNTS_RIBBONGROUPS_CLOSINGACCOUNTS', 'TabAccounts', 'Accounts.Operations', 'Accounts.Operations', N'التشغيل', 'Operations', 'RibbonButton', 'PERM_NAV_ACCOUNTS_OPERATIONS', 10),
        (1, 1, 'TABACCOUNTS_RIBBONGROUPS_CLOSINGACCOUNTS_ACCOUNTS_TRADING', 'TABACCOUNTS_RIBBONGROUPS_CLOSINGACCOUNTS', 'TabAccounts', 'Accounts.Trading', 'Accounts.Trading', N'المتاجرة', 'Trading', 'RibbonButton', 'PERM_NAV_ACCOUNTS_TRADING', 20),
        (1, 1, 'TABACCOUNTS_RIBBONGROUPS_CLOSINGACCOUNTS_ACCOUNTS_PROFITLOSS', 'TABACCOUNTS_RIBBONGROUPS_CLOSINGACCOUNTS', 'TabAccounts', 'Accounts.ProfitLoss', 'Accounts.ProfitLoss', N'أرباح خسائر', 'Profit & Loss', 'RibbonButton', 'PERM_NAV_ACCOUNTS_PROFITLOSS', 30),
        (1, 1, 'TABACCOUNTS_ACCOUNTS_FINANCIALSTATEMENTS_ACCOUNTS_BALANCESHEET', 'TABACCOUNTS_ACCOUNTS_FINANCIALSTATEMENTS', 'TabAccounts', 'Accounts.BalanceSheet', 'Accounts.BalanceSheet', N'الميزانية', 'Balance Sheet', 'RibbonButton', 'PERM_NAV_ACCOUNTS_BALANCESHEET', 10),
        (1, 1, 'TABACCOUNTS_ACCOUNTS_FINANCIALSTATEMENTS_ACCOUNTS_INCOMESTATEMENT', 'TABACCOUNTS_ACCOUNTS_FINANCIALSTATEMENTS', 'TabAccounts', 'Accounts.IncomeStatement', 'Accounts.IncomeStatement', N'قائمة الدخل', 'Income Statement', 'RibbonButton', 'PERM_NAV_ACCOUNTS_INCOMESTATEMENT', 20),
        (1, 1, 'TABACCOUNTS_ACCOUNTS_FINANCIALSTATEMENTS_ACCOUNTS_CASHFLOWSTATEMENT', 'TABACCOUNTS_ACCOUNTS_FINANCIALSTATEMENTS', 'TabAccounts', 'Accounts.CashFlowStatement', 'Accounts.CashFlowStatement', N'قائمة التدفق النقدي', 'Cash Flow Statement', 'RibbonButton', 'PERM_NAV_ACCOUNTS_CASHFLOWSTATEMENT', 30),
        (1, 1, 'TABACCOUNTS_RIBBONGROUPS_ANALYSIS_ACCOUNTS_DORMANTACCOUNTS', 'TABACCOUNTS_RIBBONGROUPS_ANALYSIS', 'TabAccounts', 'Accounts.DormantAccounts', 'Accounts.DormantAccounts', N'الحسابات الراكدة', 'Dormant Accounts', 'RibbonButton', 'PERM_NAV_ACCOUNTS_DORMANTACCOUNTS', 10),
        (1, 1, 'TABACCOUNTS_RIBBONGROUPS_ANALYSIS_ACCOUNTS_AGINGRECEIVABLES', 'TABACCOUNTS_RIBBONGROUPS_ANALYSIS', 'TabAccounts', 'Accounts.AgingReceivables', 'Accounts.AgingReceivables', N'أعمار الذمم', 'Aging Receivables', 'RibbonButton', 'PERM_NAV_ACCOUNTS_AGINGRECEIVABLES', 20),
        (1, 1, 'TABACCOUNTS_RIBBONGROUPS_ANALYSIS_ACCOUNTS_COLLECTIONRATES', 'TABACCOUNTS_RIBBONGROUPS_ANALYSIS', 'TabAccounts', 'Accounts.CollectionRates', 'Accounts.CollectionRates', N'نسب التحصيل', 'Collection Rates', 'RibbonButton', 'PERM_NAV_ACCOUNTS_COLLECTIONRATES', 30),
        (1, 1, 'TABACCOUNTS_RIBBONGROUPS_ANALYSIS_ACCOUNTS_ACCOUNTCOMPARISON', 'TABACCOUNTS_RIBBONGROUPS_ANALYSIS', 'TabAccounts', 'Accounts.AccountComparison', 'Accounts.AccountComparison', N'مقارنة حساب', 'Account Comparison', 'RibbonButton', 'PERM_NAV_ACCOUNTS_ACCOUNTCOMPARISON', 40),
        (1, 1, 'TABACCOUNTS_RIBBONGROUPS_ANALYSIS_RIBBONGROUPS_ANALYSIS', 'TABACCOUNTS_RIBBONGROUPS_ANALYSIS', 'TabAccounts', 'RibbonGroups.Analysis.تحليلماليمحلي', 'RibbonGroups.Analysis.تحليلماليمحلي', N'تحليل مالي محلي', 'تحليل مالي محلي', 'RibbonButton', 'PERM_NAV_RIBBONGROUPS_ANALYSIS', 50),
        (1, 1, 'TABACCOUNTS_RIBBONGROUPS_ANALYSIS_RIBBONGROUPS_ANALYSIS_AI', 'TABACCOUNTS_RIBBONGROUPS_ANALYSIS', 'TabAccounts', 'RibbonGroups.Analysis.تحليلماليAI', 'RibbonGroups.Analysis.تحليلماليAI', N'تحليل مالي AI', 'تحليل مالي AI', 'RibbonButton', 'PERM_NAV_RIBBONGROUPS_ANALYSIS_AI', 60),
        (1, 1, 'TABBONDS_BONDS_TITLE_BONDS_ENTRYVOUCHER', 'TABBONDS_BONDS_TITLE', 'TabBonds', 'Bonds.EntryVoucher', 'Bonds.EntryVoucher', N'سند قيد', 'Entry Voucher', 'RibbonButton', 'PERM_NAV_BONDS_ENTRYVOUCHER', 10),
        (1, 1, 'TABBONDS_BONDS_TITLE_BONDS_RECEIPTVOUCHER', 'TABBONDS_BONDS_TITLE', 'TabBonds', 'Bonds.ReceiptVoucher', 'Bonds.ReceiptVoucher', N'سند قبض', 'Receipt Voucher', 'RibbonButton', 'PERM_NAV_BONDS_RECEIPTVOUCHER', 20),
        (1, 1, 'TABBONDS_BONDS_TITLE_BONDS_PAYMENTVOUCHER', 'TABBONDS_BONDS_TITLE', 'TabBonds', 'Bonds.PaymentVoucher', 'Bonds.PaymentVoucher', N'سند دفع', 'Payment Voucher', 'RibbonButton', 'PERM_NAV_BONDS_PAYMENTVOUCHER', 30),
        (1, 1, 'TABBONDS_BONDS_TITLE_BONDS_JOURNALVOUCHER', 'TABBONDS_BONDS_TITLE', 'TabBonds', 'Bonds.JournalVoucher', 'Bonds.JournalVoucher', N'سند يومية', 'Journal Voucher', 'RibbonButton', 'PERM_NAV_BONDS_JOURNALVOUCHER', 40),
        (1, 1, 'TABBONDS_BONDS_TITLE_BONDS_CASHJOURNAL', 'TABBONDS_BONDS_TITLE', 'TabBonds', 'Bonds.CashJournal', 'Bonds.CashJournal', N'يومية الصندوق', 'Cash Journal', 'RibbonButton', 'PERM_NAV_BONDS_CASHJOURNAL', 50),
        (1, 1, 'TABBONDS_BONDS_TITLE_BONDS_DEFINEVOUCHERTYPES', 'TABBONDS_BONDS_TITLE', 'TabBonds', 'Bonds.DefineVoucherTypes', 'Bonds.DefineVoucherTypes', N'تعريف أنماط السندات', 'Define Voucher Types', 'RibbonButton', 'PERM_NAV_BONDS_DEFINEVOUCHERTYPES', 60),
        (1, 1, 'TABBONDS_RIBBONGROUPS_INSTALLMENTS_BONDS_INSTALLMENT', 'TABBONDS_RIBBONGROUPS_INSTALLMENTS', 'TabBonds', 'Bonds.Installment', 'Bonds.Installment', N'تقسيط المبالغ', 'Installment', 'RibbonButton', 'PERM_NAV_BONDS_INSTALLMENT', 10),
        (1, 1, 'TABBONDS_RIBBONGROUPS_INSTALLMENTS_BONDS_SEARCHINSTALLMENT', 'TABBONDS_RIBBONGROUPS_INSTALLMENTS', 'TabBonds', 'Bonds.SearchInstallment', 'Bonds.SearchInstallment', N'بحث تقسيط المبالغ', 'Search Installment', 'RibbonButton', 'PERM_NAV_BONDS_SEARCHINSTALLMENT', 20),
        (1, 1, 'TABBONDS_RIBBONGROUPS_SECURITIES_BONDS_RECEIPTCHEQUE', 'TABBONDS_RIBBONGROUPS_SECURITIES', 'TabBonds', 'Bonds.ReceiptCheque', 'Bonds.ReceiptCheque', N'شيك قبض', 'Receipt Cheque', 'RibbonButton', 'PERM_NAV_BONDS_RECEIPTCHEQUE', 10),
        (1, 1, 'TABBONDS_RIBBONGROUPS_SECURITIES_BONDS_PAYMENTCHEQUE', 'TABBONDS_RIBBONGROUPS_SECURITIES', 'TabBonds', 'Bonds.PaymentCheque', 'Bonds.PaymentCheque', N'شيك دفع', 'Payment Cheque', 'RibbonButton', 'PERM_NAV_BONDS_PAYMENTCHEQUE', 20),
        (1, 1, 'TABBONDS_RIBBONGROUPS_SECURITIES_BONDS_DEFINESECURITIES', 'TABBONDS_RIBBONGROUPS_SECURITIES', 'TabBonds', 'Bonds.DefineSecurities', 'Bonds.DefineSecurities', N'تعريف الأوراق المالية', 'Define Securities', 'RibbonButton', 'PERM_NAV_BONDS_DEFINESECURITIES', 30),
        (1, 1, 'TABBONDS_RIBBONGROUPS_SECURITIES_BONDS_SEARCHSECURITIES', 'TABBONDS_RIBBONGROUPS_SECURITIES', 'TabBonds', 'Bonds.SearchSecurities', 'Bonds.SearchSecurities', N'بحث الأوراق المالية', 'Search Securities', 'RibbonButton', 'PERM_NAV_BONDS_SEARCHSECURITIES', 40),
        (1, 1, 'TABBONDS_RIBBONGROUPS_PAYMENTS_BONDS_PAYMENTTYPES', 'TABBONDS_RIBBONGROUPS_PAYMENTS', 'TabBonds', 'Bonds.PaymentTypes', 'Bonds.PaymentTypes', N'أنماط الدفعات', 'Payment Types', 'RibbonButton', 'PERM_NAV_BONDS_PAYMENTTYPES', 10),
        (1, 1, 'TABBONDS_RIBBONGROUPS_PAYMENTS_BONDS_DEFINEPAYMENTTYPES', 'TABBONDS_RIBBONGROUPS_PAYMENTS', 'TabBonds', 'Bonds.DefinePaymentTypes', 'Bonds.DefinePaymentTypes', N'تعريف أنماط الدفعات', 'Define Payment Types', 'RibbonButton', 'PERM_NAV_BONDS_DEFINEPAYMENTTYPES', 20),
        (1, 1, 'TABBONDS_RIBBONGROUPS_MONITORING_BONDS_MONITORVOUCHERS', 'TABBONDS_RIBBONGROUPS_MONITORING', 'TabBonds', 'Bonds.MonitorVouchers', 'Bonds.MonitorVouchers', N'مراقبة وتعديل السندات', 'Monitor and Adjust Vouchers', 'RibbonButton', 'PERM_NAV_BONDS_MONITORVOUCHERS', 10),
        (1, 1, 'TABINVOICES_INVOICES_TITLE_INVOICES_TRANSFER', 'TABINVOICES_INVOICES_TITLE', 'TabInvoices', 'Invoices.Transfer', 'Invoices.Transfer', N'مناقلة', 'Transfer', 'RibbonButton', 'PERM_NAV_INVOICES_TRANSFER', 10),
        (1, 1, 'TABINVOICES_INVOICES_TITLE_INVOICES_OPENINGSTOCK', 'TABINVOICES_INVOICES_TITLE', 'TabInvoices', 'Invoices.OpeningStock', 'Invoices.OpeningStock', N'فاتورة بضاعة أول المدة', 'Opening Stock Invoice', 'RibbonButton', 'PERM_NAV_INVOICES_OPENINGSTOCK', 20),
        (1, 1, 'TABINVOICES_INVOICES_TITLE_INVOICES_MATERIALENTRY', 'TABINVOICES_INVOICES_TITLE', 'TabInvoices', 'Invoices.MaterialEntry', 'Invoices.MaterialEntry', N'فاتورة إدخال مواد', 'Material Entry Invoice', 'RibbonButton', 'PERM_NAV_INVOICES_MATERIALENTRY', 30),
        (1, 1, 'TABINVOICES_INVOICES_TITLE_INVOICES_MATERIALEXIT', 'TABINVOICES_INVOICES_TITLE', 'TabInvoices', 'Invoices.MaterialExit', 'Invoices.MaterialExit', N'فاتورة إخراج مواد', 'Material Exit Invoice', 'RibbonButton', 'PERM_NAV_INVOICES_MATERIALEXIT', 40),
        (1, 1, 'TABINVOICES_INVOICES_PURCHASES_INVOICES_PURCHASEINVOICE', 'TABINVOICES_INVOICES_PURCHASES', 'TabInvoices', 'Invoices.PurchaseInvoice', 'Invoices.PurchaseInvoice', N'فاتورة مشتريات', 'Purchase Invoice', 'RibbonButton', 'PERM_NAV_INVOICES_PURCHASEINVOICE', 10),
        (1, 1, 'TABINVOICES_INVOICES_PURCHASES_INVOICES_PURCHASERETURN', 'TABINVOICES_INVOICES_PURCHASES', 'TabInvoices', 'Invoices.PurchaseReturn', 'Invoices.PurchaseReturn', N'فاتورة مردودات مشتريات', 'Purchase Return Invoice', 'RibbonButton', 'PERM_NAV_INVOICES_PURCHASERETURN', 20),
        (1, 1, 'TABINVOICES_INVOICES_SALES_INVOICES_SALESINVOICE', 'TABINVOICES_INVOICES_SALES', 'TabInvoices', 'Invoices.SalesInvoice', 'Invoices.SalesInvoice', N'فاتورة مبيعات', 'Sales Invoice', 'RibbonButton', 'PERM_NAV_INVOICES_SALESINVOICE', 10),
        (1, 1, 'TABINVOICES_INVOICES_SALES_INVOICES_SALESRETURN', 'TABINVOICES_INVOICES_SALES', 'TabInvoices', 'Invoices.SalesReturn', 'Invoices.SalesReturn', N'فاتورة مردودات مبيعات', 'Sales Return Invoice', 'RibbonButton', 'PERM_NAV_INVOICES_SALESRETURN', 20),
        (1, 1, 'TABINVOICES_INVOICES_SALES_INVOICES_INVENTORYCOUNT', 'TABINVOICES_INVOICES_SALES', 'TabInvoices', 'Invoices.InventoryCount', 'Invoices.InventoryCount', N'فاتورة محضر جرد', 'Inventory Count Invoice', 'RibbonButton', 'PERM_NAV_INVOICES_INVENTORYCOUNT', 30),
        (1, 1, 'TABINVOICES_INVOICES_SALES_INVOICES_PRINTBARCODE', 'TABINVOICES_INVOICES_SALES', 'TabInvoices', 'Invoices.PrintBarcode', 'Invoices.PrintBarcode', N'طباعة الباركود', 'Print Barcode', 'RibbonButton', 'PERM_NAV_INVOICES_PRINTBARCODE', 40),
        (1, 1, 'TABINVOICES_RIBBONGROUPS_GENERAL_INVOICES_DEFINEINVOICES', 'TABINVOICES_RIBBONGROUPS_GENERAL', 'TabInvoices', 'Invoices.DefineInvoices', 'Invoices.DefineInvoices', N'تعريف الفواتير', 'Define Invoices', 'RibbonButton', 'PERM_NAV_INVOICES_DEFINEINVOICES', 10),
        (1, 1, 'TABINVOICES_RIBBONGROUPS_GENERAL_INVOICES_SEARCHINVOICES', 'TABINVOICES_RIBBONGROUPS_GENERAL', 'TabInvoices', 'Invoices.SearchInvoices', 'Invoices.SearchInvoices', N'بحث الفواتير', 'Search Invoices', 'RibbonButton', 'PERM_NAV_INVOICES_SEARCHINVOICES', 20),
        (1, 1, 'TABINVOICES_RIBBONGROUPS_GENERAL_INVOICES_CASHSALES', 'TABINVOICES_RIBBONGROUPS_GENERAL', 'TabInvoices', 'Invoices.CashSales', 'Invoices.CashSales', N'فواتير المبيعات النقدية', 'Cash Sales Invoices', 'RibbonButton', 'PERM_NAV_INVOICES_CASHSALES', 30),
        (1, 1, 'TABINVOICES_RIBBONGROUPS_GENERAL_INVOICES_CLOSECASH', 'TABINVOICES_RIBBONGROUPS_GENERAL', 'TabInvoices', 'Invoices.CloseCash', 'Invoices.CloseCash', N'إغلاق الصندوق', 'Close Cash', 'RibbonButton', 'PERM_NAV_INVOICES_CLOSECASH', 40),
        (1, 1, 'TABINVOICES_RIBBONGROUPS_GENERAL_INVOICES_QUOTATION', 'TABINVOICES_RIBBONGROUPS_GENERAL', 'TabInvoices', 'Invoices.Quotation', 'Invoices.Quotation', N'عرض سعر', 'Quotation', 'RibbonButton', 'PERM_NAV_INVOICES_QUOTATION', 50),
        (1, 1, 'TABINVOICES_RIBBONGROUPS_GENERAL_INVOICES_SEARCHQUOTATIONS', 'TABINVOICES_RIBBONGROUPS_GENERAL', 'TabInvoices', 'Invoices.SearchQuotations', 'Invoices.SearchQuotations', N'بحث عروض السعر', 'Search Quotations', 'RibbonButton', 'PERM_NAV_INVOICES_SEARCHQUOTATIONS', 60),
        (1, 1, 'TABINVOICES_RIBBONGROUPS_GENERAL_INVOICES_INVOICEPROFITS', 'TABINVOICES_RIBBONGROUPS_GENERAL', 'TabInvoices', 'Invoices.InvoiceProfits', 'Invoices.InvoiceProfits', N'أرباح الفواتير', 'Invoice Profits', 'RibbonButton', 'PERM_NAV_INVOICES_INVOICEPROFITS', 70),
        (1, 1, 'TABINVOICES_RIBBONGROUPS_GENERAL_INVOICES_PACKINGLIST', 'TABINVOICES_RIBBONGROUPS_GENERAL', 'TabInvoices', 'Invoices.PackingList', 'Invoices.PackingList', N'لائحة التعبئة', 'Packing List', 'RibbonButton', 'PERM_NAV_INVOICES_PACKINGLIST', 80),
        (1, 1, 'TABINVOICES_RIBBONGROUPS_OTHERTOOLS_INVOICES_COMPRESSINVOICES', 'TABINVOICES_RIBBONGROUPS_OTHERTOOLS', 'TabInvoices', 'Invoices.CompressInvoices', 'Invoices.CompressInvoices', N'ضغط الفواتير', 'Compress Invoices', 'RibbonButton', 'PERM_NAV_INVOICES_COMPRESSINVOICES', 10),
        (1, 1, 'TABINVOICES_RIBBONGROUPS_OTHERTOOLS_INVOICES_REPOSTINVOICES', 'TABINVOICES_RIBBONGROUPS_OTHERTOOLS', 'TabInvoices', 'Invoices.RepostInvoices', 'Invoices.RepostInvoices', N'إعادة ترحيل الفواتير', 'Repost Invoices', 'RibbonButton', 'PERM_NAV_INVOICES_REPOSTINVOICES', 20),
        (1, 1, 'TABPOS_RIBBONGROUPS_MANAGEMENT_POS_POINTS', 'TABPOS_RIBBONGROUPS_MANAGEMENT', 'TabPOS', 'POS.Points', 'POS.Points', N'النقاط', 'Points', 'RibbonButton', 'PERM_NAV_POS_POINTS', 10),
        (1, 1, 'TABPOS_RIBBONGROUPS_MANAGEMENT_POS_DEFINEPOS', 'TABPOS_RIBBONGROUPS_MANAGEMENT', 'TabPOS', 'POS.DefinePOS', 'POS.DefinePOS', N'تعريف نقاط البيع', 'Define POS', 'RibbonButton', 'PERM_NAV_POS_DEFINEPOS', 20),
        (1, 1, 'TABPOS_RIBBONGROUPS_MANAGEMENT_POS_POSCASHREPORT', 'TABPOS_RIBBONGROUPS_MANAGEMENT', 'TabPOS', 'POS.POSCashReport', 'POS.POSCashReport', N'تقرير صندوق نقطة بيع', 'POS Cash Report', 'RibbonButton', 'PERM_NAV_POS_POSCASHREPORT', 30),
        (1, 1, 'TABPOS_RIBBONGROUPS_MANAGEMENT_POS_POSDISCOUNTS', 'TABPOS_RIBBONGROUPS_MANAGEMENT', 'TabPOS', 'POS.POSDiscounts', 'POS.POSDiscounts', N'حسومات نقطة بيع', 'POS Discounts', 'RibbonButton', 'PERM_NAV_POS_POSDISCOUNTS', 40),
        (1, 1, 'TABPOS_RIBBONGROUPS_MANAGEMENT_POS_SYNCPOS', 'TABPOS_RIBBONGROUPS_MANAGEMENT', 'TabPOS', 'POS.SyncPOS', 'POS.SyncPOS', N'مزامنة نقاط البيع', 'Sync POS', 'RibbonButton', 'PERM_NAV_POS_SYNCPOS', 50),
        (1, 1, 'TABPOS_MENU_REPORTS_POS_ADJUSTPRICE', 'TABPOS_MENU_REPORTS', 'TabPOS', 'POS.AdjustPrice', 'POS.AdjustPrice', N'تعديل سعر مادة', 'Adjust Material Price', 'RibbonButton', 'PERM_NAV_POS_ADJUSTPRICE', 10),
        (1, 1, 'TABPOS_MENU_REPORTS_POS_ADJUSTQUANTITY', 'TABPOS_MENU_REPORTS', 'TabPOS', 'POS.AdjustQuantity', 'POS.AdjustQuantity', N'تعديل كمية مادة', 'Adjust Material Quantity', 'RibbonButton', 'PERM_NAV_POS_ADJUSTQUANTITY', 20),
        (1, 1, 'TABPOS_MENU_REPORTS_POS_DELETEMATERIAL', 'TABPOS_MENU_REPORTS', 'TabPOS', 'POS.DeleteMaterial', 'POS.DeleteMaterial', N'حذف مادة', 'Delete Material', 'RibbonButton', 'PERM_NAV_POS_DELETEMATERIAL', 30),
        (1, 1, 'TABORDERS_RIBBONGROUPS_ORDERS_ORDERS_PURCHASEORDER', 'TABORDERS_RIBBONGROUPS_ORDERS', 'TabOrders', 'Orders.PurchaseOrder', 'Orders.PurchaseOrder', N'طلبية شراء', 'Purchase Order', 'RibbonButton', 'PERM_NAV_ORDERS_PURCHASEORDER', 10),
        (1, 1, 'TABORDERS_RIBBONGROUPS_ORDERS_ORDERS_SALESORDER', 'TABORDERS_RIBBONGROUPS_ORDERS', 'TabOrders', 'Orders.SalesOrder', 'Orders.SalesOrder', N'طلبية بيع', 'Sales Order', 'RibbonButton', 'PERM_NAV_ORDERS_SALESORDER', 20),
        (1, 1, 'TABORDERS_RIBBONGROUPS_GENERAL_ORDERS_DEFINEORDERS', 'TABORDERS_RIBBONGROUPS_GENERAL', 'TabOrders', 'Orders.DefineOrders', 'Orders.DefineOrders', N'تعريف الطلبيات', 'Define Orders', 'RibbonButton', 'PERM_NAV_ORDERS_DEFINEORDERS', 10),
        (1, 1, 'TABORDERS_RIBBONGROUPS_GENERAL_ORDERS_ORDERRECEIPTDELIVERY', 'TABORDERS_RIBBONGROUPS_GENERAL', 'TabOrders', 'Orders.OrderReceiptDelivery', 'Orders.OrderReceiptDelivery', N'فواتير استلام وتسليم الطلبيات', 'Order Receipt and Delivery Invoices', 'RibbonButton', 'PERM_NAV_ORDERS_ORDERRECEIPTDELIVERY', 20),
        (1, 1, 'TABORDERS_RIBBONGROUPS_GENERAL_ORDERS_TRACKORDERS', 'TABORDERS_RIBBONGROUPS_GENERAL', 'TabOrders', 'Orders.TrackOrders', 'Orders.TrackOrders', N'متابعة الطلبيات', 'Track Orders', 'RibbonButton', 'PERM_NAV_ORDERS_TRACKORDERS', 30),
        (1, 1, 'TABORDERS_RIBBONGROUPS_GENERAL_ORDERS_ORDERPAYMENTS', 'TABORDERS_RIBBONGROUPS_GENERAL', 'TabOrders', 'Orders.OrderPayments', 'Orders.OrderPayments', N'دفعات الطلبيات', 'Order Payments', 'RibbonButton', 'PERM_NAV_ORDERS_ORDERPAYMENTS', 40),
        (1, 1, 'TABORDERS_RIBBONGROUPS_GENERAL_ORDERS_SEARCHORDERS', 'TABORDERS_RIBBONGROUPS_GENERAL', 'TabOrders', 'Orders.SearchOrders', 'Orders.SearchOrders', N'بحث الطلبيات', 'Search Orders', 'RibbonButton', 'PERM_NAV_ORDERS_SEARCHORDERS', 50),
        (1, 1, 'TABCUSTOMERS_RIBBONGROUPS_CARDS_CUSTOMERS_CUSTOMERCARD', 'TABCUSTOMERS_RIBBONGROUPS_CARDS', 'TabCustomers', 'Customers.CustomerCard', 'Customers.CustomerCard', N'بطاقة عميل', 'Customer Card', 'RibbonButton', 'PERM_NAV_CUSTOMERS_CUSTOMERCARD', 10),
        (1, 1, 'TABCUSTOMERS_RIBBONGROUPS_CARDS_CUSTOMERS_CUSTOMERPRICES', 'TABCUSTOMERS_RIBBONGROUPS_CARDS', 'TabCustomers', 'Customers.CustomerPrices', 'Customers.CustomerPrices', N'أسعار عميل', 'Customer Prices', 'RibbonButton', 'PERM_NAV_CUSTOMERS_CUSTOMERPRICES', 20),
        (1, 1, 'TABCUSTOMERS_RIBBONGROUPS_CARDS_CUSTOMERS_CUSTOMERDISCOUNTS', 'TABCUSTOMERS_RIBBONGROUPS_CARDS', 'TabCustomers', 'Customers.CustomerDiscounts', 'Customers.CustomerDiscounts', N'حسومات عميل', 'Customer Discounts', 'RibbonButton', 'PERM_NAV_CUSTOMERS_CUSTOMERDISCOUNTS', 30),
        (1, 1, 'TABCUSTOMERS_RIBBONGROUPS_CARDS_CUSTOMERS_AREAS', 'TABCUSTOMERS_RIBBONGROUPS_CARDS', 'TabCustomers', 'Customers.Areas', 'Customers.Areas', N'مناطق', 'Areas', 'RibbonButton', 'PERM_NAV_CUSTOMERS_AREAS', 40),
        (1, 1, 'TABCUSTOMERS_RIBBONGROUPS_TARGETS_CUSTOMERS_ASSIGNTARGETS', 'TABCUSTOMERS_RIBBONGROUPS_TARGETS', 'TabCustomers', 'Customers.AssignTargets', 'Customers.AssignTargets', N'تخصيص أهداف العملاء', 'Assign Customer Targets', 'RibbonButton', 'PERM_NAV_CUSTOMERS_ASSIGNTARGETS', 10),
        (1, 1, 'TABCUSTOMERS_RIBBONGROUPS_TARGETS_CUSTOMERS_TARGETSREPORT', 'TABCUSTOMERS_RIBBONGROUPS_TARGETS', 'TabCustomers', 'Customers.TargetsReport', 'Customers.TargetsReport', N'تقرير أهداف العملاء', 'Targets Report', 'RibbonButton', 'PERM_NAV_CUSTOMERS_TARGETSREPORT', 20),
        (1, 1, 'TABCUSTOMERS_RIBBONGROUPS_FOLLOWUP_CUSTOMERS_SEARCHCUSTOMERS', 'TABCUSTOMERS_RIBBONGROUPS_FOLLOWUP', 'TabCustomers', 'Customers.SearchCustomers', 'Customers.SearchCustomers', N'بحث العملاء', 'Search Customers', 'RibbonButton', 'PERM_NAV_CUSTOMERS_SEARCHCUSTOMERS', 10),
        (1, 1, 'TABCUSTOMERS_RIBBONGROUPS_FOLLOWUP_CUSTOMERS_CUSTOMERDUE', 'TABCUSTOMERS_RIBBONGROUPS_FOLLOWUP', 'TabCustomers', 'Customers.CustomerDue', 'Customers.CustomerDue', N'استحقاق عميل', 'Customer Due', 'RibbonButton', 'PERM_NAV_CUSTOMERS_CUSTOMERDUE', 20),
        (1, 1, 'TABCUSTOMERS_RIBBONGROUPS_FOLLOWUP_CUSTOMERS_LINKPAYMENTS', 'TABCUSTOMERS_RIBBONGROUPS_FOLLOWUP', 'TabCustomers', 'Customers.LinkPayments', 'Customers.LinkPayments', N'ربط دفعات العميل', 'Link Customer Payments', 'RibbonButton', 'PERM_NAV_CUSTOMERS_LINKPAYMENTS', 30),
        (1, 1, 'TABCUSTOMERS_RIBBONGROUPS_FOLLOWUP_CUSTOMERS_SEARCHDUES', 'TABCUSTOMERS_RIBBONGROUPS_FOLLOWUP', 'TabCustomers', 'Customers.SearchDues', 'Customers.SearchDues', N'بحث الاستحقاقات', 'Search Dues', 'RibbonButton', 'PERM_NAV_CUSTOMERS_SEARCHDUES', 40),
        (1, 1, 'TABCUSTOMERS_RIBBONGROUPS_REPORTS_CUSTOMERS_CUSTOMERBALANCE', 'TABCUSTOMERS_RIBBONGROUPS_REPORTS', 'TabCustomers', 'Customers.CustomerBalance', 'Customers.CustomerBalance', N'رصيد العملاء', 'Customer Balance', 'RibbonButton', 'PERM_NAV_CUSTOMERS_CUSTOMERBALANCE', 10),
        (1, 1, 'TABCUSTOMERS_RIBBONGROUPS_REPORTS_CUSTOMERS_BALANCEACCOUNTS', 'TABCUSTOMERS_RIBBONGROUPS_REPORTS', 'TabCustomers', 'Customers.BalanceAccounts', 'Customers.BalanceAccounts', N'ترصيد حسابات العملاء', 'Balance Customer Accounts', 'RibbonButton', 'PERM_NAV_CUSTOMERS_BALANCEACCOUNTS', 20),
        (1, 1, 'TABCUSTOMERS_RIBBONGROUPS_REPORTS_CUSTOMERS_EDITCUSTOMERS', 'TABCUSTOMERS_RIBBONGROUPS_REPORTS', 'TabCustomers', 'Customers.EditCustomers', 'Customers.EditCustomers', N'تعديل العملاء', 'Edit Customers', 'RibbonButton', 'PERM_NAV_CUSTOMERS_EDITCUSTOMERS', 30),
        (1, 1, 'TABCUSTOMERS_RIBBONGROUPS_REPORTS_CUSTOMERS_CUSTOMERGROUPS', 'TABCUSTOMERS_RIBBONGROUPS_REPORTS', 'TabCustomers', 'Customers.CustomerGroups', 'Customers.CustomerGroups', N'مجموعات العملاء', 'Customer Groups', 'RibbonButton', 'PERM_NAV_CUSTOMERS_CUSTOMERGROUPS', 40),
        (1, 1, 'TABCUSTOMERS_RIBBONGROUPS_REPORTS_CUSTOMERS_CUSTOMERREPORTS', 'TABCUSTOMERS_RIBBONGROUPS_REPORTS', 'TabCustomers', 'Customers.CustomerReports', 'Customers.CustomerReports', N'تقارير العملاء', 'Customer Reports', 'RibbonButton', 'PERM_NAV_CUSTOMERS_CUSTOMERREPORTS', 50),
        (1, 1, 'TABSALESREP_RIBBONGROUPS_CARDS_SALESREP_SALESREPCARD', 'TABSALESREP_RIBBONGROUPS_CARDS', 'TabSalesRep', 'SalesRep.SalesRepCard', 'SalesRep.SalesRepCard', N'بطاقة مندوب', 'Sales Rep Card', 'RibbonButton', 'PERM_NAV_SALESREP_SALESREPCARD', 10),
        (1, 1, 'TABSALESREP_RIBBONGROUPS_CARDS_SALESREP_SALESREPGROUPS', 'TABSALESREP_RIBBONGROUPS_CARDS', 'TabSalesRep', 'SalesRep.SalesRepGroups', 'SalesRep.SalesRepGroups', N'مجموعات المندوب', 'Sales Rep Groups', 'RibbonButton', 'PERM_NAV_SALESREP_SALESREPGROUPS', 20),
        (1, 1, 'TABSALESREP_RIBBONGROUPS_TARGETS_SALESREP_ASSIGNSALESREPTARGETS', 'TABSALESREP_RIBBONGROUPS_TARGETS', 'TabSalesRep', 'SalesRep.AssignSalesRepTargets', 'SalesRep.AssignSalesRepTargets', N'تخصيص أهداف المندوبين', 'Assign Sales Rep Targets', 'RibbonButton', 'PERM_NAV_SALESREP_ASSIGNSALESREPTARGETS', 10),
        (1, 1, 'TABSALESREP_RIBBONGROUPS_TARGETS_SALESREP_SALESREPTARGETSREPORT', 'TABSALESREP_RIBBONGROUPS_TARGETS', 'TabSalesRep', 'SalesRep.SalesRepTargetsReport', 'SalesRep.SalesRepTargetsReport', N'تقرير أهداف المندوبين', 'Sales Rep Targets Report', 'RibbonButton', 'PERM_NAV_SALESREP_SALESREPTARGETSREPORT', 20),
        (1, 1, 'TABSALESREP_RIBBONGROUPS_FOLLOWUP_CUSTOMERS_SEARCHCUSTOMERS', 'TABSALESREP_RIBBONGROUPS_FOLLOWUP', 'TabSalesRep', 'Customers.SearchCustomers', 'Customers.SearchCustomers', N'بحث العملاء', 'Search Customers', 'RibbonButton', 'PERM_NAV_CUSTOMERS_SEARCHCUSTOMERS', 10),
        (1, 1, 'TABSALESREP_RIBBONGROUPS_FOLLOWUP_SALESREP_SALESREPMOVEMENT', 'TABSALESREP_RIBBONGROUPS_FOLLOWUP', 'TabSalesRep', 'SalesRep.SalesRepMovement', 'SalesRep.SalesRepMovement', N'حركة مندوب', 'Sales Rep Movement', 'RibbonButton', 'PERM_NAV_SALESREP_SALESREPMOVEMENT', 20),
        (1, 1, 'TABSALESREP_RIBBONGROUPS_FOLLOWUP_SALESREP_SALESREPCOLLECTIONS', 'TABSALESREP_RIBBONGROUPS_FOLLOWUP', 'TabSalesRep', 'SalesRep.SalesRepCollections', 'SalesRep.SalesRepCollections', N'تحصيلات المندوب', 'Sales Rep Collections', 'RibbonButton', 'PERM_NAV_SALESREP_SALESREPCOLLECTIONS', 30),
        (1, 1, 'TABSALESREP_RIBBONGROUPS_MOBILEDEVICES_SALESREP_DEVICECARDS', 'TABSALESREP_RIBBONGROUPS_MOBILEDEVICES', 'TabSalesRep', 'SalesRep.DeviceCards', 'SalesRep.DeviceCards', N'بطاقات الأجهزة الكفية', 'Device Cards', 'RibbonButton', 'PERM_NAV_SALESREP_DEVICECARDS', 10),
        (1, 1, 'TABSALESREP_RIBBONGROUPS_MOBILEDEVICES_SALESREP_DEVICEROUTES', 'TABSALESREP_RIBBONGROUPS_MOBILEDEVICES', 'TabSalesRep', 'SalesRep.DeviceRoutes', 'SalesRep.DeviceRoutes', N'مسارات الأجهزة الكفية', 'Device Routes', 'RibbonButton', 'PERM_NAV_SALESREP_DEVICEROUTES', 20),
        (1, 1, 'TABMANUFACTURING_RIBBONGROUPS_MANAGEMENT_MANUFACTURING_MANUFACTURINGMODELS', 'TABMANUFACTURING_RIBBONGROUPS_MANAGEMENT', 'TabManufacturing', 'Manufacturing.ManufacturingModels', 'Manufacturing.ManufacturingModels', N'نماذج التصنيع', 'Manufacturing Models', 'RibbonButton', 'PERM_NAV_MANUFACTURING_MANUFACTURINGMODELS', 10),
        (1, 1, 'TABMANUFACTURING_RIBBONGROUPS_MANAGEMENT_MANUFACTURING_MANUFACTURINGPROCESS', 'TABMANUFACTURING_RIBBONGROUPS_MANAGEMENT', 'TabManufacturing', 'Manufacturing.ManufacturingProcess', 'Manufacturing.ManufacturingProcess', N'عملية تصنيع', 'Manufacturing Process', 'RibbonButton', 'PERM_NAV_MANUFACTURING_MANUFACTURINGPROCESS', 20),
        (1, 1, 'TABMANUFACTURING_RIBBONGROUPS_MANAGEMENT_MANUFACTURING_MANUFACTURINGFEASIBILITY', 'TABMANUFACTURING_RIBBONGROUPS_MANAGEMENT', 'TabManufacturing', 'Manufacturing.ManufacturingFeasibility', 'Manufacturing.ManufacturingFeasibility', N'إمكانية التصنيع', 'Manufacturing Feasibility', 'RibbonButton', 'PERM_NAV_MANUFACTURING_MANUFACTURINGFEASIBILITY', 30),
        (1, 1, 'TABMANUFACTURING_RIBBONGROUPS_MANAGEMENT_MANUFACTURING_SEARCHMANUFACTURING', 'TABMANUFACTURING_RIBBONGROUPS_MANAGEMENT', 'TabManufacturing', 'Manufacturing.SearchManufacturing', 'Manufacturing.SearchManufacturing', N'بحث التصنيع', 'Search Manufacturing', 'RibbonButton', 'PERM_NAV_MANUFACTURING_SEARCHMANUFACTURING', 40),
        (1, 1, 'TABMANUFACTURING_RIBBONGROUPS_COSTVARIANCES_MANUFACTURING_MANUFACTURINGCOSTVARIA', 'TABMANUFACTURING_RIBBONGROUPS_COSTVARIANCES', 'TabManufacturing', 'Manufacturing.ManufacturingCostVariance', 'Manufacturing.ManufacturingCostVariance', N'انحراف تكاليف المواد المصنعة', 'Manufactured Material Cost Variance', 'RibbonButton', 'PERM_NAV_MANUFACTURING_MANUFACTURINGCOSTVARIANCE', 10),
        (1, 1, 'TABMANUFACTURING_RIBBONGROUPS_COSTVARIANCES_MANUFACTURING_RAWMATERIALCOSTVARIANC', 'TABMANUFACTURING_RIBBONGROUPS_COSTVARIANCES', 'TabManufacturing', 'Manufacturing.RawMaterialCostVariance', 'Manufacturing.RawMaterialCostVariance', N'انحراف تكاليف المواد الأولية', 'Raw Material Cost Variance', 'RibbonButton', 'PERM_NAV_MANUFACTURING_RAWMATERIALCOSTVARIANCE', 20),
        (1, 1, 'TABMANUFACTURING_RIBBONGROUPS_COSTVARIANCES_MANUFACTURING_ADDITIONALCOSTVARIANCE', 'TABMANUFACTURING_RIBBONGROUPS_COSTVARIANCES', 'TabManufacturing', 'Manufacturing.AdditionalCostVariance', 'Manufacturing.AdditionalCostVariance', N'انحراف التكاليف الإضافية', 'Additional Cost Variance', 'RibbonButton', 'PERM_NAV_MANUFACTURING_ADDITIONALCOSTVARIANCE', 30),
        (1, 1, 'TABMANUFACTURING_RIBBONGROUPS_COSTVARIANCES_MANUFACTURING_MANUFACTUREDMATERIALCO', 'TABMANUFACTURING_RIBBONGROUPS_COSTVARIANCES', 'TabManufacturing', 'Manufacturing.ManufacturedMaterialCostVariance', 'Manufacturing.ManufacturedMaterialCostVariance', N'انحراف التكاليف الإضافية للمواد المصنعة', 'Additional Cost Variance for Manufactured Materials', 'RibbonButton', 'PERM_NAV_MANUFACTURING_MANUFACTUREDMATERIALCOSTVARIANCE', 40),
        (1, 1, 'TABMANUFACTURING_RIBBONGROUPS_REPORTS_MANUFACTURING_MANUFACTUREDMATERIALCOSTS', 'TABMANUFACTURING_RIBBONGROUPS_REPORTS', 'TabManufacturing', 'Manufacturing.ManufacturedMaterialCosts', 'Manufacturing.ManufacturedMaterialCosts', N'تكاليف المواد المصنعة', 'Manufactured Material Costs', 'RibbonButton', 'PERM_NAV_MANUFACTURING_MANUFACTUREDMATERIALCOSTS', 10),
        (1, 1, 'TABMANUFACTURING_RIBBONGROUPS_REPORTS_MANUFACTURING_REPOSTMANUFACTURING', 'TABMANUFACTURING_RIBBONGROUPS_REPORTS', 'TabManufacturing', 'Manufacturing.RepostManufacturing', 'Manufacturing.RepostManufacturing', N'إعادة ترحيل عمليات التصنيع', 'Repost Manufacturing Operations', 'RibbonButton', 'PERM_NAV_MANUFACTURING_REPOSTMANUFACTURING', 20),
        (1, 1, 'TABBANKS_RIBBONGROUPS_MANAGEMENT_BANKS_DEFINEBANKS', 'TABBANKS_RIBBONGROUPS_MANAGEMENT', 'TabBanks', 'Banks.DefineBanks', 'Banks.DefineBanks', N'تعريف البنوك', 'Define Banks', 'RibbonButton', 'PERM_NAV_BANKS_DEFINEBANKS', 10),
        (1, 1, 'TABBANKS_RIBBONGROUPS_MANAGEMENT_BANKS_BANKESTIMATE', 'TABBANKS_RIBBONGROUPS_MANAGEMENT', 'TabBanks', 'Banks.BankEstimate', 'Banks.BankEstimate', N'كشف البنك التقديري', 'Bank Estimate Statement', 'RibbonButton', 'PERM_NAV_BANKS_BANKESTIMATE', 20),
        (1, 1, 'TABBANKS_RIBBONGROUPS_MANAGEMENT_BANKS_BANKRECONCILIATION', 'TABBANKS_RIBBONGROUPS_MANAGEMENT', 'TabBanks', 'Banks.BankReconciliation', 'Banks.BankReconciliation', N'تسوية بنكية', 'Bank Reconciliation', 'RibbonButton', 'PERM_NAV_BANKS_BANKRECONCILIATION', 30),
        (1, 1, 'TABBANKS_RIBBONGROUPS_MANAGEMENT_BANKS_BANKBALANCES', 'TABBANKS_RIBBONGROUPS_MANAGEMENT', 'TabBanks', 'Banks.BankBalances', 'Banks.BankBalances', N'أرصدة البنوك', 'Bank Balances', 'RibbonButton', 'PERM_NAV_BANKS_BANKBALANCES', 40),
        (1, 1, 'TABREPORTS_RIBBONGROUPS_REPORTS_REPORTS_STATISTICS', 'TABREPORTS_RIBBONGROUPS_REPORTS', 'TabReports', 'Reports.Statistics', 'Reports.Statistics', N'إحصائيات', 'Statistics', 'RibbonButton', 'PERM_NAV_REPORTS_STATISTICS', 10),
        (1, 1, 'TABREPORTS_RIBBONGROUPS_REPORTS_REPORTS_MATERIALOVERVIEW', 'TABREPORTS_RIBBONGROUPS_REPORTS', 'TabReports', 'Reports.MaterialOverview', 'Reports.MaterialOverview', N'لمحة عن مادة', 'Material Overview', 'RibbonButton', 'PERM_NAV_REPORTS_MATERIALOVERVIEW', 20),
        (1, 1, 'TABREPORTS_RIBBONGROUPS_REPORTS_REPORTS_CUSTOMEROVERVIEW', 'TABREPORTS_RIBBONGROUPS_REPORTS', 'TabReports', 'Reports.CustomerOverview', 'Reports.CustomerOverview', N'لمحة عن عميل', 'Customer Overview', 'RibbonButton', 'PERM_NAV_REPORTS_CUSTOMEROVERVIEW', 30),
        (1, 1, 'TABREPORTS_RIBBONGROUPS_REPORTS_REPORTS_CUSTOMREPORTS', 'TABREPORTS_RIBBONGROUPS_REPORTS', 'TabReports', 'Reports.CustomReports', 'Reports.CustomReports', N'تقارير مخصصة', 'Custom Reports', 'RibbonButton', 'PERM_NAV_REPORTS_CUSTOMREPORTS', 40),
        (1, 1, 'TABREPORTS_RIBBONGROUPS_REPORTS_REPORTS_CUSTOMIZEREPORTS', 'TABREPORTS_RIBBONGROUPS_REPORTS', 'TabReports', 'Reports.CustomizeReports', 'Reports.CustomizeReports', N'تخصيص التقارير', 'Customize Reports', 'RibbonButton', 'PERM_NAV_REPORTS_CUSTOMIZEREPORTS', 50),
        (1, 1, 'TABTOOLS_RIBBONGROUPS_TOOLS_TOOLS_CALCULATOR', 'TABTOOLS_RIBBONGROUPS_TOOLS', 'TabTools', 'Tools.Calculator', 'Tools.Calculator', N'آلة حاسبة', 'Calculator', 'RibbonButton', 'PERM_NAV_TOOLS_CALCULATOR', 10),
        (1, 1, 'TABTOOLS_RIBBONGROUPS_TOOLS_TOOLS_KEYBOARD', 'TABTOOLS_RIBBONGROUPS_TOOLS', 'TabTools', 'Tools.Keyboard', 'Tools.Keyboard', N'لوحة المفاتيح', 'Keyboard', 'RibbonButton', 'PERM_NAV_TOOLS_KEYBOARD', 20),
        (1, 1, 'TABTOOLS_RIBBONGROUPS_TOOLS_TOOLS_OPTIONS', 'TABTOOLS_RIBBONGROUPS_TOOLS', 'TabTools', 'Tools.Options', 'Tools.Options', N'خيارات', 'Options', 'RibbonButton', 'PERM_NAV_TOOLS_OPTIONS', 30),
        (1, 1, 'TABTOOLS_RIBBONGROUPS_TOOLS_TOOLS_MAINTENANCEWIZARD', 'TABTOOLS_RIBBONGROUPS_TOOLS', 'TabTools', 'Tools.MaintenanceWizard', 'Tools.MaintenanceWizard', N'معالج الصيانة', 'Maintenance Wizard', 'RibbonButton', 'PERM_NAV_TOOLS_MAINTENANCEWIZARD', 40),
        (1, 1, 'TABTOOLS_RIBBONGROUPS_TOOLS_TOOLS_BACKUP', 'TABTOOLS_RIBBONGROUPS_TOOLS', 'TabTools', 'Tools.Backup', 'Tools.Backup', N'النسخ الاحتياطي', 'Backup', 'RibbonButton', 'PERM_NAV_TOOLS_BACKUP', 50),
        (1, 1, 'TABTOOLS_TOOLS_LANGUAGE_TOOLS_LANGUAGE', 'TABTOOLS_TOOLS_LANGUAGE', 'TabTools', 'Tools.Language.عربي', 'Tools.Language.عربي', N'🌐 عربي', '🌐 عربي', 'OnLanguageArabicClick', 'PERM_NAV_TOOLS_LANGUAGE', 10),
        (1, 1, 'TABTOOLS_TOOLS_LANGUAGE_TOOLS_LANGUAGE_ENGLISH', 'TABTOOLS_TOOLS_LANGUAGE', 'TabTools', 'Tools.Language.ENGLISH', 'Tools.Language.ENGLISH', N'🌐 English', '🌐 English', 'OnLanguageEnglishClick', 'PERM_NAV_TOOLS_LANGUAGE_ENGLISH', 20),
        (1, 1, 'TABTOOLS_TOOLS_LANGUAGE_TOOLS_LANGUAGE_FRAN_AIS', 'TABTOOLS_TOOLS_LANGUAGE', 'TabTools', 'Tools.Language.FRANÇAIS', 'Tools.Language.FRANÇAIS', N'🌐 Français', '🌐 Français', 'OnLanguageFrenchClick', 'PERM_NAV_TOOLS_LANGUAGE_FRAN_AIS', 30),
        (1, 1, 'TABTOOLS_TOOLS_LANGUAGE_TOOLS_LANGUAGE_T_RK_E', 'TABTOOLS_TOOLS_LANGUAGE', 'TabTools', 'Tools.Language.TÜRKÇE', 'Tools.Language.TÜRKÇE', N'🌐 Türkçe', '🌐 Türkçe', 'OnLanguageTurkishClick', 'PERM_NAV_TOOLS_LANGUAGE_T_RK_E', 40),
        (1, 1, 'TABTOOLS_RIBBONGROUPS_SECURITY_TOOLS_CHANGEPASSWORD', 'TABTOOLS_RIBBONGROUPS_SECURITY', 'TabTools', 'Tools.ChangePassword', 'Tools.ChangePassword', N'تغيير كلمة المرور', 'Change Password', 'RibbonButton', 'PERM_NAV_TOOLS_CHANGEPASSWORD', 10),
        (1, 1, 'TABTOOLS_RIBBONGROUPS_SECURITY_TOOLS_ACTIVITYLOG', 'TABTOOLS_RIBBONGROUPS_SECURITY', 'TabTools', 'Tools.ActivityLog', 'Tools.ActivityLog', N'مسجل الحركات', 'Activity Log', 'RibbonButton', 'PERM_NAV_TOOLS_ACTIVITYLOG', 20),
        (1, 1, 'TABTOOLS_RIBBONGROUPS_ADVANCED_TOOLS_ADDONS', 'TABTOOLS_RIBBONGROUPS_ADVANCED', 'TabTools', 'Tools.Addons', 'Tools.Addons', N'إضافات البرنامج', 'Program Add-ons', 'RibbonButton', 'PERM_NAV_TOOLS_ADDONS', 10),
        (1, 1, 'TABTOOLS_RIBBONGROUPS_ADVANCED_TOOLS_AI', 'TABTOOLS_RIBBONGROUPS_ADVANCED', 'TabTools', 'Tools.AI', 'Tools.AI', N'الذكاء الصناعي', 'Artificial Intelligence', 'RibbonButton', 'PERM_NAV_TOOLS_AI', 20),
        (1, 1, 'TABOTHERTOOLS_RIBBONGROUPS_MANAGEMENT_OTHERTOOLS_ROTATION', 'TABOTHERTOOLS_RIBBONGROUPS_MANAGEMENT', 'TabOtherTools', 'OtherTools.Rotation', 'OtherTools.Rotation', N'التدوير', 'Rotation', 'RibbonButton', 'PERM_NAV_OTHERTOOLS_ROTATION', 10),
        (1, 1, 'TABOTHERTOOLS_RIBBONGROUPS_MANAGEMENT_OTHERTOOLS_PERMISSIONS', 'TABOTHERTOOLS_RIBBONGROUPS_MANAGEMENT', 'TabOtherTools', 'OtherTools.Permissions', 'OtherTools.Permissions', N'صلاحيات', 'Permissions', 'RibbonButton', 'PERM_NAV_OTHERTOOLS_PERMISSIONS', 20),
        (1, 1, 'TABOTHERTOOLS_RIBBONGROUPS_MANAGEMENT_OTHERTOOLS_PERMISSIONTEMPLATES', 'TABOTHERTOOLS_RIBBONGROUPS_MANAGEMENT', 'TabOtherTools', 'OtherTools.PermissionTemplates', 'OtherTools.PermissionTemplates', N'قوالب الصلاحيات', 'Permission Templates', 'RibbonButton', 'PERM_NAV_OTHERTOOLS_PERMISSIONTEMPLATES', 30),
        (1, 1, 'TABOTHERTOOLS_RIBBONGROUPS_MANAGEMENT_OTHERTOOLS_CUSTOMFIELDS', 'TABOTHERTOOLS_RIBBONGROUPS_MANAGEMENT', 'TabOtherTools', 'OtherTools.CustomFields', 'OtherTools.CustomFields', N'حقول مخصصة', 'Custom Fields', 'RibbonButton', 'PERM_NAV_OTHERTOOLS_CUSTOMFIELDS', 40),
        (1, 1, 'TABOTHERTOOLS_RIBBONGROUPS_DEFINITIONS_OTHERTOOLS_UNITSOFMEASURE', 'TABOTHERTOOLS_RIBBONGROUPS_DEFINITIONS', 'TabOtherTools', 'OtherTools.UnitsOfMeasure', 'OtherTools.UnitsOfMeasure', N'تعريف وحدات القياس', 'Define Units of Measure', 'RibbonButton', 'PERM_NAV_OTHERTOOLS_UNITSOFMEASURE', 10),
        (1, 1, 'TABOTHERTOOLS_RIBBONGROUPS_DEFINITIONS_OTHERTOOLS_PAYMENTMETHODS', 'TABOTHERTOOLS_RIBBONGROUPS_DEFINITIONS', 'TabOtherTools', 'OtherTools.PaymentMethods', 'OtherTools.PaymentMethods', N'تعريف طرق الدفع', 'Define Payment Methods', 'RibbonButton', 'PERM_NAV_OTHERTOOLS_PAYMENTMETHODS', 20),
        (1, 1, 'TABOTHERTOOLS_RIBBONGROUPS_DEFINITIONS_OTHERTOOLS_MATERIALSPECS', 'TABOTHERTOOLS_RIBBONGROUPS_DEFINITIONS', 'TabOtherTools', 'OtherTools.MaterialSpecs', 'OtherTools.MaterialSpecs', N'تعريف مواصفات المواد', 'Define Material Specifications', 'RibbonButton', 'PERM_NAV_OTHERTOOLS_MATERIALSPECS', 30),
        (1, 1, 'TABOTHERTOOLS_RIBBONGROUPS_DELIVERY_OTHERTOOLS_DRIVERCARD', 'TABOTHERTOOLS_RIBBONGROUPS_DELIVERY', 'TabOtherTools', 'OtherTools.DriverCard', 'OtherTools.DriverCard', N'بطاقة سائق', 'Driver Card', 'RibbonButton', 'PERM_NAV_OTHERTOOLS_DRIVERCARD', 10),
        (1, 1, 'TABOTHERTOOLS_RIBBONGROUPS_DELIVERY_OTHERTOOLS_DELIVERYPRICES', 'TABOTHERTOOLS_RIBBONGROUPS_DELIVERY', 'TabOtherTools', 'OtherTools.DeliveryPrices', 'OtherTools.DeliveryPrices', N'أسعار التوصيل', 'Delivery Prices', 'RibbonButton', 'PERM_NAV_OTHERTOOLS_DELIVERYPRICES', 20),
        (1, 1, 'TABOTHERTOOLS_RIBBONGROUPS_DELIVERY_OTHERTOOLS_PICKUPREQUESTS', 'TABOTHERTOOLS_RIBBONGROUPS_DELIVERY', 'TabOtherTools', 'OtherTools.PickupRequests', 'OtherTools.PickupRequests', N'طلبات استلام', 'Pickup Requests', 'RibbonButton', 'PERM_NAV_OTHERTOOLS_PICKUPREQUESTS', 30),
        (1, 1, 'TABOTHERTOOLS_RIBBONGROUPS_DELIVERY_OTHERTOOLS_SEARCHDELIVERY', 'TABOTHERTOOLS_RIBBONGROUPS_DELIVERY', 'TabOtherTools', 'OtherTools.SearchDelivery', 'OtherTools.SearchDelivery', N'بحث التوصيل', 'Search Delivery', 'RibbonButton', 'PERM_NAV_OTHERTOOLS_SEARCHDELIVERY', 40),
        (1, 1, 'TABOTHERTOOLS_RIBBONGROUPS_DELIVERY_OTHERTOOLS_CLOSEDRIVERCASH', 'TABOTHERTOOLS_RIBBONGROUPS_DELIVERY', 'TabOtherTools', 'OtherTools.CloseDriverCash', 'OtherTools.CloseDriverCash', N'إغلاق صندوق سائق', 'Close Driver Cash', 'RibbonButton', 'PERM_NAV_OTHERTOOLS_CLOSEDRIVERCASH', 50),
        (1, 1, 'TABVIEW_RIBBONGROUPS_APPEARANCE_RIBBONGROUPS_APPEARANCE', 'TABVIEW_RIBBONGROUPS_APPEARANCE', 'TabView', 'RibbonGroups.Appearance.الوضعالليلي', 'RibbonGroups.Appearance.الوضعالليلي', N'🌙 الوضع الليلي', '🌙 الوضع الليلي', 'RibbonButton', 'PERM_NAV_RIBBONGROUPS_APPEARANCE', 10),
        (1, 1, 'TABVIEW_RIBBONGROUPS_APPEARANCE_RIBBONGROUPS_APPEARANCE', 'TABVIEW_RIBBONGROUPS_APPEARANCE', 'TabView', 'RibbonGroups.Appearance.الوضعالنهاري', 'RibbonGroups.Appearance.الوضعالنهاري', N'☀️ الوضع النهاري', '☀️ الوضع النهاري', 'RibbonButton', 'PERM_NAV_RIBBONGROUPS_APPEARANCE', 20),
        (1, 1, 'TABVIEW_RIBBONGROUPS_APPEARANCE_SHELL_TOGGLETHEME', 'TABVIEW_RIBBONGROUPS_APPEARANCE', 'TabView', 'Shell.ToggleTheme', 'Shell.ToggleTheme', N'تبديل المظهر', 'Toggle theme', 'RibbonButton', 'PERM_NAV_SHELL_TOGGLETHEME', 30),
        (1, 1, 'TABVIEW_RIBBONGROUPS_TREES_ACCOUNTS_CHARTOFACCOUNTS', 'TABVIEW_RIBBONGROUPS_TREES', 'TabView', 'Accounts.ChartOfAccounts', 'Accounts.ChartOfAccounts', N'شجرة الحسابات', 'Chart of Accounts', 'RibbonButton', 'PERM_NAV_ACCOUNTS_CHARTOFACCOUNTS', 10),
        (1, 1, 'TABVIEW_RIBBONGROUPS_TREES_INVENTORY_MATERIALTREE', 'TABVIEW_RIBBONGROUPS_TREES', 'TabView', 'Inventory.MaterialTree', 'Inventory.MaterialTree', N'شجرة المواد', 'Material Tree', 'RibbonButton', 'PERM_NAV_INVENTORY_MATERIALTREE', 20),
        (1, 1, 'TABVIEW_RIBBONGROUPS_TREES_VIEW_MANUFACTURINGTREE', 'TABVIEW_RIBBONGROUPS_TREES', 'TabView', 'View.ManufacturingTree', 'View.ManufacturingTree', N'شجرة التصنيع', 'Manufacturing Tree', 'RibbonButton', 'PERM_NAV_VIEW_MANUFACTURINGTREE', 30),
        (1, 1, 'TABVIEW_RIBBONGROUPS_TREES_VIEW_COSTCENTERTREE', 'TABVIEW_RIBBONGROUPS_TREES', 'TabView', 'View.CostCenterTree', 'View.CostCenterTree', N'شجرة مراكز الكلف', 'Cost Center Tree', 'RibbonButton', 'PERM_NAV_VIEW_COSTCENTERTREE', 40),
        (1, 1, 'TABVIEW_RIBBONGROUPS_INFORMATION_VIEW_INFOWINDOW', 'TABVIEW_RIBBONGROUPS_INFORMATION', 'TabView', 'View.InfoWindow', 'View.InfoWindow', N'نافذة المعلومات', 'Information Window', 'RibbonButton', 'PERM_NAV_VIEW_INFOWINDOW', 10),
        (1, 1, 'TABVIEW_RIBBONGROUPS_INFORMATION_OTHERTOOLS_PAYMENTMETHODS', 'TABVIEW_RIBBONGROUPS_INFORMATION', 'TabView', 'OtherTools.PaymentMethods', 'OtherTools.PaymentMethods', N'تعريف طرق الدفع', 'Define Payment Methods', 'RibbonButton', 'PERM_NAV_OTHERTOOLS_PAYMENTMETHODS', 20),
        (1, 1, 'TABVIEW_RIBBONGROUPS_INFORMATION_VIEW_COMPANYINFO', 'TABVIEW_RIBBONGROUPS_INFORMATION', 'TabView', 'View.CompanyInfo', 'View.CompanyInfo', N'معلومات الشركة', 'Company Information', 'RibbonButton', 'PERM_NAV_VIEW_COMPANYINFO', 30),
        (1, 1, 'TABVIEW_RIBBONGROUPS_INFORMATION_VIEW_EXPORTDATA', 'TABVIEW_RIBBONGROUPS_INFORMATION', 'TabView', 'View.ExportData', 'View.ExportData', N'تصدير البيانات', 'Export Data', 'RibbonButton', 'PERM_NAV_VIEW_EXPORTDATA', 40),
        (1, 1, 'TABEXIT_RIBBONGROUPS_EXITALT_EXIT_SCREENSAVER', 'TABEXIT_RIBBONGROUPS_EXITALT', 'TabExit', 'Exit.ScreenSaver', 'Exit.ScreenSaver', N'شاشة حماية', 'Screen Saver', 'RibbonButton', 'PERM_NAV_EXIT_SCREENSAVER', 10),
        (1, 1, 'TABEXIT_RIBBONGROUPS_EXITALT_EXIT_SWITCHCOMPANY', 'TABEXIT_RIBBONGROUPS_EXITALT', 'TabExit', 'Exit.SwitchCompany', 'Exit.SwitchCompany', N'تبديل الشركة', 'Switch Company', 'RibbonButton', 'PERM_NAV_EXIT_SWITCHCOMPANY', 20),
        (1, 1, 'TABEXIT_RIBBONGROUPS_EXITALT_MENU_EXIT', 'TABEXIT_RIBBONGROUPS_EXITALT', 'TabExit', 'Menu.Exit', 'Menu.Exit', N'خروج', 'Exit', 'RibbonButton', 'PERM_NAV_MENU_EXIT', 30),
        (1, 1, 'TABEXIT_RIBBONGROUPS_EXITALT_EXIT_EXITANDSHUTDOWN', 'TABEXIT_RIBBONGROUPS_EXITALT', 'TabExit', 'Exit.ExitAndShutdown', 'Exit.ExitAndShutdown', N'خروج وإطفاء الحاسب', 'Exit and Shutdown Computer', 'RibbonButton', 'PERM_NAV_EXIT_EXITANDSHUTDOWN', 40),
        (1, 1, 'TABHELP_RIBBONGROUPS_UPDATES_HELP_CHECKUPDATES', 'TABHELP_RIBBONGROUPS_UPDATES', 'TabHelp', 'Help.CheckUpdates', 'Help.CheckUpdates', N'تحقق من وجود تحديثات', 'Check for Updates', 'RibbonButton', 'PERM_NAV_HELP_CHECKUPDATES', 10),
        (1, 1, 'TABHELP_RIBBONGROUPS_UPDATES_HELP_UPDATEFROMFILE', 'TABHELP_RIBBONGROUPS_UPDATES', 'TabHelp', 'Help.UpdateFromFile', 'Help.UpdateFromFile', N'تحديث من ملف', 'Update from File', 'RibbonButton', 'PERM_NAV_HELP_UPDATEFROMFILE', 20),
        (1, 1, 'TABHELP_RIBBONGROUPS_SUPPORT_HELP_INSTRUCTIONS', 'TABHELP_RIBBONGROUPS_SUPPORT', 'TabHelp', 'Help.Instructions', 'Help.Instructions', N'تعليمات البرنامج', 'Program Instructions', 'RibbonButton', 'PERM_NAV_HELP_INSTRUCTIONS', 10),
        (1, 1, 'TABHELP_RIBBONGROUPS_SUPPORT_HELP_TECHNICALSUPPORT', 'TABHELP_RIBBONGROUPS_SUPPORT', 'TabHelp', 'Help.TechnicalSupport', 'Help.TechnicalSupport', N'الدعم الفني', 'Technical Support', 'RibbonButton', 'PERM_NAV_HELP_TECHNICALSUPPORT', 20),
        (1, 1, 'TABHELP_RIBBONGROUPS_SUPPORT_HELP_SUGGESTIONS', 'TABHELP_RIBBONGROUPS_SUPPORT', 'TabHelp', 'Help.Suggestions', 'Help.Suggestions', N'اقتراحاتكم', 'Your Suggestions', 'RibbonButton', 'PERM_NAV_HELP_SUGGESTIONS', 30),
        (1, 1, 'TABHELP_RIBBONGROUPS_LICENSING_HELP_RENEWLICENSE', 'TABHELP_RIBBONGROUPS_LICENSING', 'TabHelp', 'Help.RenewLicense', 'Help.RenewLicense', N'تجديد الترخيص', 'Renew License', 'RibbonButton', 'PERM_NAV_HELP_RENEWLICENSE', 10),
        (1, 1, 'TABHELP_RIBBONGROUPS_LICENSING_HELP_ABOUT', 'TABHELP_RIBBONGROUPS_LICENSING', 'TabHelp', 'Help.About', 'Help.About', N'حول البرنامج', 'About Program', 'RibbonButton', 'PERM_NAV_HELP_ABOUT', 20)
    ) AS Source (TenantID, CompanyID, ItemCode, GroupCode, TabCode, LocalizationKey, ActionKey, TitleAR, TitleEN, HandlerType, PermissionCode, DisplayOrder)
    ON Target.TenantID = Source.TenantID AND Target.CompanyID = Source.CompanyID AND Target.ItemCode = Source.ItemCode
    WHEN MATCHED THEN UPDATE SET
        GroupCode = Source.GroupCode,
        TabCode = Source.TabCode,
        LocalizationKey = Source.LocalizationKey,
        ActionKey = Source.ActionKey,
        TitleAR = Source.TitleAR,
        TitleEN = Source.TitleEN,
        HandlerType = Source.HandlerType,
        PermissionID = (SELECT PermissionID FROM sec.Permissions WHERE PermissionCode = Source.PermissionCode),
        DisplayOrder = Source.DisplayOrder,
        IsActive = 1,
        IsDeleted = 0,
        UpdatedAt = SYSDATETIME()
    WHEN NOT MATCHED THEN
        INSERT (TenantID, CompanyID, ItemCode, GroupCode, TabCode, LocalizationKey, ActionKey, TitleAR, TitleEN, HandlerType, PermissionID, DisplayOrder)
        VALUES (Source.TenantID, Source.CompanyID, Source.ItemCode, Source.GroupCode, Source.TabCode, Source.LocalizationKey, Source.ActionKey, Source.TitleAR, Source.TitleEN, Source.HandlerType,
                (SELECT PermissionID FROM sec.Permissions WHERE PermissionCode = Source.PermissionCode), Source.DisplayOrder);

    COMMIT TRANSACTION;
    RAISERROR(N'âœ… [SUCCESS] Navigation seed completed.', 0, 1) WITH NOWAIT;
END TRY
BEGIN CATCH
    IF (XACT_STATE()) <> 0 ROLLBACK TRANSACTION;
    DECLARE @ErrMsg NVARCHAR(4000) = ERROR_MESSAGE();
    RAISERROR(N'âŒ [FATAL ERROR] sds_nav.sql failed: %s', 16, 1, @ErrMsg);
END CATCH;
GO
