-- ═════════════════════════════════════════════════════════════════════════════════
-- FILE: dba/sys/nav.sql
-- SYSTEM: ShouTech ERP Enterprise Core
-- MODULE: Main Menu + Ribbon Navigation Schema (Commercial / Tier-1)
-- VERSION: 1.0.0
-- DESCRIPTION:
--   Canonical database model for WPF shell navigation:
--     • sys.MainMenuItems   — top menu bar (17 modules)
--     • sys.RibbonTabs      — ribbon tabs linked to menu entries
--     • sys.RibbonGroups    — ribbon groups within tabs
--     • sys.RibbonItems     — ribbon commands / actions
--
-- DESIGN PRINCIPLES:
--   ✓ Multi-tenant (TenantID + CompanyID) on all business tables
--   ✓ Soft delete + optimistic concurrency (RowVersion)
--   ✓ RBAC integration via sec.Permissions
--   ✓ Idempotent DDL (safe to re-run)
--   ✓ Permission-filtered stored procedures for runtime UI binding
--
-- SEED DATA: dba/sds/sds_nav.sql (generated by tools/generate_nav_seed.ps1)
-- ═════════════════════════════════════════════════════════════════════════════════

SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = N'sys')
BEGIN
    EXEC('CREATE SCHEMA [sys] AUTHORIZATION [dbo];');
END;
GO

RAISERROR(N'🚀 [ENTERPRISE BUILD] Navigation schema (sys.MainMenuItems / Ribbon*)...', 0, 1) WITH NOWAIT;

BEGIN TRANSACTION;

BEGIN TRY

    -------------------------------------------------------------------------
    -- 1) sys.MainMenuItems — top-level menu bar entries
    -------------------------------------------------------------------------
    IF OBJECT_ID(N'sys.MainMenuItems', N'U') IS NULL
    BEGIN
        CREATE TABLE sys.MainMenuItems (
            MainMenuID          INT             NOT NULL IDENTITY(1,1),
            TenantID            INT             NOT NULL CONSTRAINT DF_sys_MainMenuItems_Tenant DEFAULT (1),
            CompanyID           INT             NOT NULL CONSTRAINT DF_sys_MainMenuItems_Company DEFAULT (1),
            MenuItemCode        VARCHAR(50)     NOT NULL,
            TabCode             VARCHAR(50)     NOT NULL,
            LocalizationKey     VARCHAR(200)    NOT NULL,
            IconEmoji           NVARCHAR(10)    NULL,
            ModuleCode          VARCHAR(50)     NULL,
            PermissionID        INT             NULL,
            DisplayOrder        INT             NOT NULL CONSTRAINT DF_sys_MainMenuItems_Order DEFAULT (0),
            IsActive            BIT             NOT NULL CONSTRAINT DF_sys_MainMenuItems_Active DEFAULT (1),
            IsDeleted           BIT             NOT NULL CONSTRAINT DF_sys_MainMenuItems_Deleted DEFAULT (0),
            CreatedBy           INT             NULL,
            CreatedAt           DATETIME2(7)    NOT NULL CONSTRAINT DF_sys_MainMenuItems_Created DEFAULT (SYSDATETIME()),
            UpdatedBy           INT             NULL,
            UpdatedAt           DATETIME2(7)    NULL,
            DeletedBy           INT             NULL,
            DeletedAt           DATETIME2(7)    NULL,
            RowVersion          ROWVERSION      NOT NULL,

            CONSTRAINT PK_sys_MainMenuItems PRIMARY KEY CLUSTERED (MainMenuID),
            CONSTRAINT UQ_sys_MainMenuItems_Code UNIQUE (TenantID, CompanyID, MenuItemCode),
            CONSTRAINT UQ_sys_MainMenuItems_Tab UNIQUE (TenantID, CompanyID, TabCode),
            CONSTRAINT CK_sys_MainMenuItems_DisplayOrder CHECK (DisplayOrder >= 0),
            CONSTRAINT FK_sys_MainMenuItems_Permission FOREIGN KEY (PermissionID)
                REFERENCES sec.Permissions (PermissionID)
        );
    END;

    IF NOT EXISTS (
        SELECT 1 FROM sys.indexes
        WHERE name = N'IX_sys_MainMenuItems_ActiveOrder'
          AND object_id = OBJECT_ID(N'sys.MainMenuItems')
    )
    BEGIN
        CREATE NONCLUSTERED INDEX IX_sys_MainMenuItems_ActiveOrder
        ON sys.MainMenuItems (TenantID, CompanyID, DisplayOrder)
        INCLUDE (MenuItemCode, TabCode, LocalizationKey, IconEmoji, ModuleCode, PermissionID)
        WHERE IsActive = 1 AND IsDeleted = 0;
    END;

    -------------------------------------------------------------------------
    -- 2) sys.RibbonTabs — ribbon tabs (1:1 with menu in current shell design)
    -------------------------------------------------------------------------
    IF OBJECT_ID(N'sys.RibbonTabs', N'U') IS NULL
    BEGIN
        CREATE TABLE sys.RibbonTabs (
            RibbonTabID         INT             NOT NULL IDENTITY(1,1),
            TenantID            INT             NOT NULL CONSTRAINT DF_sys_RibbonTabs_Tenant DEFAULT (1),
            CompanyID           INT             NOT NULL CONSTRAINT DF_sys_RibbonTabs_Company DEFAULT (1),
            TabCode             VARCHAR(50)     NOT NULL,
            MenuItemCode        VARCHAR(50)     NULL,
            LocalizationKey     VARCHAR(200)    NOT NULL,
            HeaderIcon          NVARCHAR(10)    NULL,
            ModuleCode          VARCHAR(50)     NULL,
            PermissionID        INT             NULL,
            DisplayOrder        INT             NOT NULL CONSTRAINT DF_sys_RibbonTabs_Order DEFAULT (0),
            IsActive            BIT             NOT NULL CONSTRAINT DF_sys_RibbonTabs_Active DEFAULT (1),
            IsDeleted           BIT             NOT NULL CONSTRAINT DF_sys_RibbonTabs_Deleted DEFAULT (0),
            CreatedBy           INT             NULL,
            CreatedAt           DATETIME2(7)    NOT NULL CONSTRAINT DF_sys_RibbonTabs_Created DEFAULT (SYSDATETIME()),
            UpdatedBy           INT             NULL,
            UpdatedAt           DATETIME2(7)    NULL,
            DeletedBy           INT             NULL,
            DeletedAt           DATETIME2(7)    NULL,
            RowVersion          ROWVERSION      NOT NULL,

            CONSTRAINT PK_sys_RibbonTabs PRIMARY KEY CLUSTERED (RibbonTabID),
            CONSTRAINT UQ_sys_RibbonTabs_Code UNIQUE (TenantID, CompanyID, TabCode),
            CONSTRAINT CK_sys_RibbonTabs_DisplayOrder CHECK (DisplayOrder >= 0),
            CONSTRAINT FK_sys_RibbonTabs_Permission FOREIGN KEY (PermissionID)
                REFERENCES sec.Permissions (PermissionID)
        );
    END;

    IF NOT EXISTS (
        SELECT 1 FROM sys.indexes
        WHERE name = N'IX_sys_RibbonTabs_MenuLink'
          AND object_id = OBJECT_ID(N'sys.RibbonTabs')
    )
    BEGIN
        CREATE NONCLUSTERED INDEX IX_sys_RibbonTabs_MenuLink
        ON sys.RibbonTabs (TenantID, CompanyID, MenuItemCode, DisplayOrder)
        WHERE IsActive = 1 AND IsDeleted = 0;
    END;

    IF NOT EXISTS (
        SELECT 1 FROM sys.foreign_keys
        WHERE name = N'FK_sys_RibbonTabs_MainMenu'
          AND parent_object_id = OBJECT_ID(N'sys.RibbonTabs')
    )
    BEGIN
        ALTER TABLE sys.RibbonTabs WITH CHECK
        ADD CONSTRAINT FK_sys_RibbonTabs_MainMenu
            FOREIGN KEY (TenantID, CompanyID, MenuItemCode)
            REFERENCES sys.MainMenuItems (TenantID, CompanyID, MenuItemCode);
    END;

    -------------------------------------------------------------------------
    -- 3) sys.RibbonGroups — logical command groups inside a tab
    -------------------------------------------------------------------------
    IF OBJECT_ID(N'sys.RibbonGroups', N'U') IS NULL
    BEGIN
        CREATE TABLE sys.RibbonGroups (
            RibbonGroupID       INT             NOT NULL IDENTITY(1,1),
            TenantID            INT             NOT NULL CONSTRAINT DF_sys_RibbonGroups_Tenant DEFAULT (1),
            CompanyID           INT             NOT NULL CONSTRAINT DF_sys_RibbonGroups_Company DEFAULT (1),
            GroupCode           VARCHAR(120)    NOT NULL,
            TabCode             VARCHAR(50)     NOT NULL,
            LocalizationKey     VARCHAR(200)    NULL,
            TitleAR             NVARCHAR(150)   NOT NULL,
            TitleEN             VARCHAR(150)    NOT NULL,
            PermissionID        INT             NULL,
            DisplayOrder        INT             NOT NULL CONSTRAINT DF_sys_RibbonGroups_Order DEFAULT (0),
            IsActive            BIT             NOT NULL CONSTRAINT DF_sys_RibbonGroups_Active DEFAULT (1),
            IsDeleted           BIT             NOT NULL CONSTRAINT DF_sys_RibbonGroups_Deleted DEFAULT (0),
            CreatedBy           INT             NULL,
            CreatedAt           DATETIME2(7)    NOT NULL CONSTRAINT DF_sys_RibbonGroups_Created DEFAULT (SYSDATETIME()),
            UpdatedBy           INT             NULL,
            UpdatedAt           DATETIME2(7)    NULL,
            DeletedBy           INT             NULL,
            DeletedAt           DATETIME2(7)    NULL,
            RowVersion          ROWVERSION      NOT NULL,

            CONSTRAINT PK_sys_RibbonGroups PRIMARY KEY CLUSTERED (RibbonGroupID),
            CONSTRAINT UQ_sys_RibbonGroups_Code UNIQUE (TenantID, CompanyID, GroupCode),
            CONSTRAINT CK_sys_RibbonGroups_DisplayOrder CHECK (DisplayOrder >= 0),
            CONSTRAINT FK_sys_RibbonGroups_Permission FOREIGN KEY (PermissionID)
                REFERENCES sec.Permissions (PermissionID)
        );
    END;

    IF NOT EXISTS (
        SELECT 1 FROM sys.foreign_keys
        WHERE name = N'FK_sys_RibbonGroups_Tab'
          AND parent_object_id = OBJECT_ID(N'sys.RibbonGroups')
    )
    BEGIN
        ALTER TABLE sys.RibbonGroups WITH CHECK
        ADD CONSTRAINT FK_sys_RibbonGroups_Tab
            FOREIGN KEY (TenantID, CompanyID, TabCode)
            REFERENCES sys.RibbonTabs (TenantID, CompanyID, TabCode);
    END;

    IF NOT EXISTS (
        SELECT 1 FROM sys.indexes
        WHERE name = N'IX_sys_RibbonGroups_TabOrder'
          AND object_id = OBJECT_ID(N'sys.RibbonGroups')
    )
    BEGIN
        CREATE NONCLUSTERED INDEX IX_sys_RibbonGroups_TabOrder
        ON sys.RibbonGroups (TenantID, CompanyID, TabCode, DisplayOrder)
        INCLUDE (GroupCode, LocalizationKey, TitleAR, TitleEN, PermissionID)
        WHERE IsActive = 1 AND IsDeleted = 0;
    END;

    -------------------------------------------------------------------------
    -- 4) sys.RibbonItems — executable ribbon commands
    -------------------------------------------------------------------------
    IF OBJECT_ID(N'sys.RibbonItems', N'U') IS NULL
    BEGIN
        CREATE TABLE sys.RibbonItems (
            RibbonItemID        INT             NOT NULL IDENTITY(1,1),
            TenantID            INT             NOT NULL CONSTRAINT DF_sys_RibbonItems_Tenant DEFAULT (1),
            CompanyID           INT             NOT NULL CONSTRAINT DF_sys_RibbonItems_Company DEFAULT (1),
            ItemCode            VARCHAR(120)    NOT NULL,
            GroupCode           VARCHAR(120)    NOT NULL,
            TabCode             VARCHAR(50)     NOT NULL,
            LocalizationKey     VARCHAR(200)    NOT NULL,
            ActionKey           VARCHAR(200)    NOT NULL,
            TitleAR             NVARCHAR(150)   NOT NULL,
            TitleEN             VARCHAR(150)    NOT NULL,
            HandlerType         VARCHAR(50)     NOT NULL CONSTRAINT DF_sys_RibbonItems_Handler DEFAULT ('RibbonButton'),
            TargetViewName      VARCHAR(200)    NULL,
            TargetViewModelName VARCHAR(200)    NULL,
            PermissionID        INT             NULL,
            DisplayOrder        INT             NOT NULL CONSTRAINT DF_sys_RibbonItems_Order DEFAULT (0),
            IsActive            BIT             NOT NULL CONSTRAINT DF_sys_RibbonItems_Active DEFAULT (1),
            IsDeleted           BIT             NOT NULL CONSTRAINT DF_sys_RibbonItems_Deleted DEFAULT (0),
            CreatedBy           INT             NULL,
            CreatedAt           DATETIME2(7)    NOT NULL CONSTRAINT DF_sys_RibbonItems_Created DEFAULT (SYSDATETIME()),
            UpdatedBy           INT             NULL,
            UpdatedAt           DATETIME2(7)    NULL,
            DeletedBy           INT             NULL,
            DeletedAt           DATETIME2(7)    NULL,
            RowVersion          ROWVERSION      NOT NULL,

            CONSTRAINT PK_sys_RibbonItems PRIMARY KEY CLUSTERED (RibbonItemID),
            CONSTRAINT UQ_sys_RibbonItems_Code UNIQUE (TenantID, CompanyID, ItemCode),
            CONSTRAINT CK_sys_RibbonItems_DisplayOrder CHECK (DisplayOrder >= 0),
            CONSTRAINT CK_sys_RibbonItems_HandlerType CHECK (
                HandlerType IN (
                    'RibbonButton',
                    'OnLanguageArabicClick',
                    'OnLanguageEnglishClick',
                    'OnLanguageFrenchClick',
                    'OnLanguageTurkishClick'
                )
            ),
            CONSTRAINT FK_sys_RibbonItems_Permission FOREIGN KEY (PermissionID)
                REFERENCES sec.Permissions (PermissionID)
        );
    END;

    IF NOT EXISTS (
        SELECT 1 FROM sys.foreign_keys
        WHERE name = N'FK_sys_RibbonItems_Group'
          AND parent_object_id = OBJECT_ID(N'sys.RibbonItems')
    )
    BEGIN
        ALTER TABLE sys.RibbonItems WITH CHECK
        ADD CONSTRAINT FK_sys_RibbonItems_Group
            FOREIGN KEY (TenantID, CompanyID, GroupCode)
            REFERENCES sys.RibbonGroups (TenantID, CompanyID, GroupCode);
    END;

    IF NOT EXISTS (
        SELECT 1 FROM sys.indexes
        WHERE name = N'IX_sys_RibbonItems_GroupOrder'
          AND object_id = OBJECT_ID(N'sys.RibbonItems')
    )
    BEGIN
        CREATE NONCLUSTERED INDEX IX_sys_RibbonItems_GroupOrder
        ON sys.RibbonItems (TenantID, CompanyID, GroupCode, DisplayOrder)
        INCLUDE (ItemCode, ActionKey, TitleAR, TitleEN, HandlerType, PermissionID)
        WHERE IsActive = 1 AND IsDeleted = 0;
    END;

    IF NOT EXISTS (
        SELECT 1 FROM sys.indexes
        WHERE name = N'IX_sys_RibbonItems_ActionKey'
          AND object_id = OBJECT_ID(N'sys.RibbonItems')
    )
    BEGIN
        CREATE NONCLUSTERED INDEX IX_sys_RibbonItems_ActionKey
        ON sys.RibbonItems (TenantID, CompanyID, ActionKey)
        INCLUDE (TabCode, GroupCode, PermissionID)
        WHERE IsActive = 1 AND IsDeleted = 0;
    END;

    COMMIT TRANSACTION;
    RAISERROR(N'✅ [SUCCESS] Enterprise navigation schema deployed.', 0, 1) WITH NOWAIT;

END TRY
BEGIN CATCH
    IF (XACT_STATE()) <> 0 ROLLBACK TRANSACTION;
    DECLARE @SchemaErr NVARCHAR(4000) = ERROR_MESSAGE();
    RAISERROR(N'❌ [FATAL ERROR] nav.sql failed: %s', 16, 1, @SchemaErr);
END CATCH;
GO

-- ═════════════════════════════════════════════════════════════════════════════════
-- Runtime API — permission-aware navigation queries
-- ═════════════════════════════════════════════════════════════════════════════════

CREATE OR ALTER PROCEDURE sys.sp_GetMainMenuItems
    @UserID     INT,
    @TenantID   INT = 1,
    @CompanyID  INT = 1
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @IsSuperAdmin BIT = 0;

    SELECT @IsSuperAdmin = u.IsSuperAdmin
    FROM sec.Users u
    WHERE u.UserID = @UserID
      AND u.TenantID = @TenantID
      AND u.IsActive = 1
      AND u.IsDeleted = 0;

    ;WITH UserPermissions AS (
        SELECT DISTINCT rp.PermissionID
        FROM sec.UserRoles ur
        INNER JOIN sec.RolePermissions rp ON rp.RoleID = ur.RoleID
        WHERE ur.UserID = @UserID
    )
    SELECT
        m.MainMenuID,
        m.MenuItemCode,
        m.TabCode,
        m.LocalizationKey,
        m.IconEmoji,
        m.ModuleCode,
        m.DisplayOrder,
        m.RowVersion
    FROM sys.MainMenuItems m
    WHERE m.TenantID = @TenantID
      AND m.CompanyID = @CompanyID
      AND m.IsActive = 1
      AND m.IsDeleted = 0
      AND (
            @IsSuperAdmin = 1
            OR m.PermissionID IS NULL
            OR EXISTS (SELECT 1 FROM UserPermissions up WHERE up.PermissionID = m.PermissionID)
          )
    ORDER BY m.DisplayOrder, m.MenuItemCode;
END;
GO

CREATE OR ALTER PROCEDURE sys.sp_GetUserRibbonLayout
    @UserID     INT,
    @TabCode    VARCHAR(50) = NULL,
    @TenantID   INT = 1,
    @CompanyID  INT = 1
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @IsSuperAdmin BIT = 0;

    SELECT @IsSuperAdmin = u.IsSuperAdmin
    FROM sec.Users u
    WHERE u.UserID = @UserID
      AND u.TenantID = @TenantID
      AND u.IsActive = 1
      AND u.IsDeleted = 0;

    ;WITH UserPermissions AS (
        SELECT DISTINCT rp.PermissionID
        FROM sec.UserRoles ur
        INNER JOIN sec.RolePermissions rp ON rp.RoleID = ur.RoleID
        WHERE ur.UserID = @UserID
    )
    SELECT
        t.TabCode,
        t.LocalizationKey     AS TabLocalizationKey,
        t.HeaderIcon,
        t.ModuleCode          AS TabModuleCode,
        t.DisplayOrder        AS TabDisplayOrder,
        g.GroupCode,
        g.LocalizationKey     AS GroupLocalizationKey,
        g.TitleAR             AS GroupTitleAR,
        g.TitleEN             AS GroupTitleEN,
        g.DisplayOrder        AS GroupDisplayOrder,
        i.ItemCode,
        i.LocalizationKey     AS ItemLocalizationKey,
        i.ActionKey,
        i.TitleAR             AS ItemTitleAR,
        i.TitleEN             AS ItemTitleEN,
        i.HandlerType,
        i.TargetViewName,
        i.TargetViewModelName,
        i.DisplayOrder        AS ItemDisplayOrder,
        p.PermissionCode
    FROM sys.RibbonTabs t
    INNER JOIN sys.RibbonGroups g
        ON  g.TenantID  = t.TenantID
        AND g.CompanyID = t.CompanyID
        AND g.TabCode   = t.TabCode
        AND g.IsActive  = 1
        AND g.IsDeleted = 0
    INNER JOIN sys.RibbonItems i
        ON  i.TenantID  = g.TenantID
        AND i.CompanyID = g.CompanyID
        AND i.GroupCode = g.GroupCode
        AND i.IsActive  = 1
        AND i.IsDeleted = 0
    LEFT JOIN sec.Permissions p ON p.PermissionID = i.PermissionID
    WHERE t.TenantID = @TenantID
      AND t.CompanyID = @CompanyID
      AND t.IsActive = 1
      AND t.IsDeleted = 0
      AND (@TabCode IS NULL OR t.TabCode = @TabCode)
      AND (
            @IsSuperAdmin = 1
            OR (
                (t.PermissionID IS NULL OR EXISTS (SELECT 1 FROM UserPermissions up WHERE up.PermissionID = t.PermissionID))
                AND (g.PermissionID IS NULL OR EXISTS (SELECT 1 FROM UserPermissions up WHERE up.PermissionID = g.PermissionID))
                AND (i.PermissionID IS NULL OR EXISTS (SELECT 1 FROM UserPermissions up WHERE up.PermissionID = i.PermissionID))
            )
          )
    ORDER BY t.DisplayOrder, g.DisplayOrder, i.DisplayOrder, i.ItemCode;
END;
GO

CREATE OR ALTER VIEW sys.vw_NavigationCatalog
AS
    SELECT
        m.MenuItemCode,
        m.TabCode,
        m.LocalizationKey AS MenuLocalizationKey,
        m.ModuleCode      AS MenuModuleCode,
        t.LocalizationKey AS TabLocalizationKey,
        g.GroupCode,
        g.TitleAR         AS GroupTitleAR,
        g.TitleEN         AS GroupTitleEN,
        i.ItemCode,
        i.ActionKey,
        i.TitleAR         AS ItemTitleAR,
        i.TitleEN         AS ItemTitleEN,
        i.HandlerType,
        p.PermissionCode
    FROM sys.MainMenuItems m
    INNER JOIN sys.RibbonTabs t
        ON  t.TenantID = m.TenantID AND t.CompanyID = m.CompanyID AND t.TabCode = m.TabCode
    INNER JOIN sys.RibbonGroups g
        ON  g.TenantID = t.TenantID AND g.CompanyID = t.CompanyID AND g.TabCode = t.TabCode
    INNER JOIN sys.RibbonItems i
        ON  i.TenantID = g.TenantID AND i.CompanyID = g.CompanyID AND i.GroupCode = g.GroupCode
    LEFT JOIN sec.Permissions p ON p.PermissionID = i.PermissionID
    WHERE m.IsDeleted = 0 AND t.IsDeleted = 0 AND g.IsDeleted = 0 AND i.IsDeleted = 0;
GO
