-- PostgreSQL migration for the repository access layers.
-- Names are lower-case because unquoted PostgreSQL identifiers are folded to lower-case.

CREATE TABLE IF NOT EXISTS companies
(
    company_id uuid PRIMARY KEY,
    company_code varchar(50) NOT NULL UNIQUE,
    company_name_ar varchar(250) NOT NULL,
    company_name_en varchar(250) NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS units_of_measure
(
    uom_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id uuid NOT NULL REFERENCES companies(company_id),
    uom_code varchar(30) NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    is_deleted boolean NOT NULL DEFAULT false,
    UNIQUE (company_id, uom_code)
);

CREATE TABLE IF NOT EXISTS products
(
    product_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id uuid NOT NULL REFERENCES companies(company_id),
    product_code varchar(100) NOT NULL,
    product_name_ar varchar(250) NOT NULL,
    product_name_en varchar(250),
    category_id integer NOT NULL,
    primary_uom_id integer NOT NULL REFERENCES units_of_measure(uom_id),
    default_sale_price numeric(19,4) NOT NULL DEFAULT 0,
    default_purchase_price numeric(19,4) NOT NULL DEFAULT 0,
    cost_price numeric(19,4) NOT NULL DEFAULT 0,
    is_active boolean NOT NULL DEFAULT true,
    is_deleted boolean NOT NULL DEFAULT false,
    created_by uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_by uuid,
    updated_at timestamptz,
    deleted_by uuid,
    deleted_at timestamptz,
    UNIQUE (company_id, product_code)
);

CREATE TABLE IF NOT EXISTS journal_entries (
    journal_entry_id uuid PRIMARY KEY,
    company_id uuid NOT NULL,
    entry_date date NOT NULL,
    description varchar(500) NOT NULL CHECK (btrim(description) <> ''),
    status smallint NOT NULL DEFAULT 0 CHECK (status IN (0, 1, 2)),
    created_by varchar(100) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    posted_by varchar(100),
    posted_at timestamptz,
    reversed_by varchar(100),
    reversed_at timestamptz
);

CREATE TABLE IF NOT EXISTS journal_entry_lines (
    journal_entry_line_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    journal_entry_id uuid NOT NULL REFERENCES journal_entries(journal_entry_id),
    line_number integer NOT NULL,
    account_id uuid NOT NULL,
    debit numeric(19,4) NOT NULL DEFAULT 0,
    credit numeric(19,4) NOT NULL DEFAULT 0,
    cost_center varchar(100),
    note varchar(500),
    UNIQUE (journal_entry_id, line_number),
    CHECK (debit >= 0 AND credit >= 0 AND ((debit > 0 AND credit = 0) OR (credit > 0 AND debit = 0)))
);

CREATE TABLE IF NOT EXISTS journal_audit_events (
    journal_audit_event_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    journal_entry_id uuid NOT NULL REFERENCES journal_entries(journal_entry_id),
    event_type smallint NOT NULL CHECK (event_type IN (1, 2, 3)),
    actor varchar(100) NOT NULL,
    event_at timestamptz NOT NULL DEFAULT now(),
    details varchar(1000)
);

CREATE TABLE IF NOT EXISTS stock_balances (
    stock_balance_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id uuid NOT NULL,
    warehouse_id bigint NOT NULL,
    product_id integer NOT NULL,
    available_qty numeric(18,4) NOT NULL DEFAULT 0,
    last_cost numeric(18,6),
    last_updated timestamptz NOT NULL DEFAULT now(),
    is_deleted boolean NOT NULL DEFAULT false,
    UNIQUE (company_id, warehouse_id, product_id)
);

CREATE TABLE IF NOT EXISTS stock_movements (
    movement_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id uuid NOT NULL,
    movement_type varchar(30) NOT NULL,
    movement_date timestamptz NOT NULL DEFAULT now(),
    warehouse_id_to bigint,
    product_id integer NOT NULL,
    quantity numeric(18,4) NOT NULL CHECK (quantity > 0),
    unit_cost numeric(18,6),
    reference_table varchar(50),
    notes text,
    created_by uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);
