CREATE TABLE IF NOT EXISTS fiscal_years (
    fiscal_year_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id uuid NOT NULL REFERENCES companies(company_id), fiscal_year integer NOT NULL,
    database_name varchar(200) NOT NULL, start_date date NOT NULL, end_date date NOT NULL,
    is_current boolean NOT NULL DEFAULT true, is_closed boolean NOT NULL DEFAULT false,
    UNIQUE(company_id, fiscal_year)
);
CREATE TABLE IF NOT EXISTS users (
    user_id uuid PRIMARY KEY, company_id uuid NOT NULL REFERENCES companies(company_id),
    username varchar(100) NOT NULL, password_hash varchar(500) NOT NULL, password_salt varchar(500) NOT NULL,
    full_name varchar(200) NOT NULL, full_name_ar varchar(200) NOT NULL, full_name_en varchar(200) NOT NULL,
    email varchar(250), must_change_password boolean NOT NULL DEFAULT false,
    is_super_admin boolean NOT NULL DEFAULT false, is_active boolean NOT NULL DEFAULT true,
    is_deleted boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE(company_id, username)
);
CREATE TABLE IF NOT EXISTS roles (
    role_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, company_id uuid NOT NULL REFERENCES companies(company_id),
    role_code varchar(50) NOT NULL, role_name varchar(150) NOT NULL, is_active boolean NOT NULL DEFAULT true,
    is_deleted boolean NOT NULL DEFAULT false, UNIQUE(company_id, role_code)
);
CREATE TABLE IF NOT EXISTS permissions (
    permission_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permission_code varchar(100) NOT NULL UNIQUE, permission_name varchar(200) NOT NULL,
    is_active boolean NOT NULL DEFAULT true
);
CREATE TABLE IF NOT EXISTS user_roles (
    user_id uuid NOT NULL REFERENCES users(user_id), role_id bigint NOT NULL REFERENCES roles(role_id),
    PRIMARY KEY(user_id, role_id)
);
CREATE TABLE IF NOT EXISTS role_permissions (
    role_id bigint NOT NULL REFERENCES roles(role_id), permission_id bigint NOT NULL REFERENCES permissions(permission_id),
    PRIMARY KEY(role_id, permission_id)
);
