-- PostgreSQL module schema. Tables are tenant-scoped and use UUID identifiers.
CREATE SCHEMA IF NOT EXISTS crm;
CREATE SCHEMA IF NOT EXISTS hr;
CREATE SCHEMA IF NOT EXISTS pos;
CREATE SCHEMA IF NOT EXISTS mfg;
CREATE SCHEMA IF NOT EXISTS ai;
CREATE SCHEMA IF NOT EXISTS audit;
CREATE SCHEMA IF NOT EXISTS mst;

CREATE TABLE IF NOT EXISTS crm.business_partners (
    partner_id uuid PRIMARY KEY, company_id uuid NOT NULL REFERENCES companies(company_id),
    partner_code varchar(50) NOT NULL, partner_type varchar(20) NOT NULL,
    name_ar varchar(250) NOT NULL, name_en varchar(250), tax_number varchar(100),
    phone varchar(50), email varchar(250), is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(company_id, partner_code)
);
CREATE TABLE IF NOT EXISTS crm.sales_orders (
    order_id uuid PRIMARY KEY, company_id uuid NOT NULL REFERENCES companies(company_id),
    partner_id uuid REFERENCES crm.business_partners(partner_id), order_number varchar(50) NOT NULL,
    order_date date NOT NULL, status varchar(30) NOT NULL DEFAULT 'DRAFT',
    total_amount numeric(19,4) NOT NULL DEFAULT 0, created_by uuid NOT NULL,
    UNIQUE(company_id, order_number)
);
CREATE TABLE IF NOT EXISTS crm.sales_order_lines (
    line_id uuid PRIMARY KEY, order_id uuid NOT NULL REFERENCES crm.sales_orders(order_id),
    product_id integer NOT NULL, quantity numeric(18,4) NOT NULL CHECK(quantity > 0),
    unit_price numeric(19,4) NOT NULL CHECK(unit_price >= 0), tax_amount numeric(19,4) NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS hr.departments (
    department_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id uuid NOT NULL REFERENCES companies(company_id), code varchar(50) NOT NULL,
    name_ar varchar(150) NOT NULL, name_en varchar(150), is_active boolean NOT NULL DEFAULT true,
    UNIQUE(company_id, code)
);
CREATE TABLE IF NOT EXISTS hr.employees (
    employee_id uuid PRIMARY KEY, company_id uuid NOT NULL REFERENCES companies(company_id),
    employee_code varchar(50) NOT NULL, full_name_ar varchar(200) NOT NULL, full_name_en varchar(200),
    department_id bigint REFERENCES hr.departments(department_id), hire_date date,
    status varchar(30) NOT NULL DEFAULT 'ACTIVE', UNIQUE(company_id, employee_code)
);
CREATE TABLE IF NOT EXISTS hr.leave_requests (
    leave_request_id uuid PRIMARY KEY, company_id uuid NOT NULL REFERENCES companies(company_id),
    employee_id uuid NOT NULL REFERENCES hr.employees(employee_id), start_date date NOT NULL,
    end_date date NOT NULL, leave_type varchar(50) NOT NULL, status varchar(30) NOT NULL DEFAULT 'PENDING',
    CHECK(end_date >= start_date)
);
CREATE TABLE IF NOT EXISTS hr.payroll_runs (
    payroll_run_id uuid PRIMARY KEY, company_id uuid NOT NULL REFERENCES companies(company_id),
    period_start date NOT NULL, period_end date NOT NULL, status varchar(30) NOT NULL DEFAULT 'DRAFT',
    UNIQUE(company_id, period_start, period_end)
);

CREATE TABLE IF NOT EXISTS pos.shifts (
    shift_id uuid PRIMARY KEY, company_id uuid NOT NULL REFERENCES companies(company_id),
    opened_by uuid NOT NULL, opened_at timestamptz NOT NULL DEFAULT now(),
    closed_at timestamptz, status varchar(20) NOT NULL DEFAULT 'OPEN'
);
CREATE TABLE IF NOT EXISTS pos.sales (
    sale_id uuid PRIMARY KEY, company_id uuid NOT NULL REFERENCES companies(company_id),
    shift_id uuid REFERENCES pos.shifts(shift_id), sale_number varchar(50) NOT NULL,
    sale_date timestamptz NOT NULL DEFAULT now(), status varchar(20) NOT NULL DEFAULT 'POSTED',
    total_amount numeric(19,4) NOT NULL DEFAULT 0, UNIQUE(company_id, sale_number)
);
CREATE TABLE IF NOT EXISTS pos.sale_lines (
    line_id uuid PRIMARY KEY, sale_id uuid NOT NULL REFERENCES pos.sales(sale_id),
    product_id integer NOT NULL, quantity numeric(18,4) NOT NULL CHECK(quantity > 0),
    unit_price numeric(19,4) NOT NULL CHECK(unit_price >= 0), discount_amount numeric(19,4) NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS pos.payments (
    payment_id uuid PRIMARY KEY, sale_id uuid NOT NULL REFERENCES pos.sales(sale_id),
    method varchar(30) NOT NULL, amount numeric(19,4) NOT NULL CHECK(amount > 0),
    reference varchar(150)
);

CREATE TABLE IF NOT EXISTS mfg.boms (
    bom_id uuid PRIMARY KEY, company_id uuid NOT NULL REFERENCES companies(company_id),
    product_id integer NOT NULL, version varchar(30) NOT NULL, is_active boolean NOT NULL DEFAULT true,
    UNIQUE(company_id, product_id, version)
);
CREATE TABLE IF NOT EXISTS mfg.bom_lines (
    bom_line_id uuid PRIMARY KEY, bom_id uuid NOT NULL REFERENCES mfg.boms(bom_id),
    component_product_id integer NOT NULL, quantity numeric(18,6) NOT NULL CHECK(quantity > 0)
);
CREATE TABLE IF NOT EXISTS mfg.work_orders (
    work_order_id uuid PRIMARY KEY, company_id uuid NOT NULL REFERENCES companies(company_id),
    order_number varchar(50) NOT NULL, product_id integer NOT NULL, planned_quantity numeric(18,4) NOT NULL,
    completed_quantity numeric(18,4) NOT NULL DEFAULT 0, status varchar(30) NOT NULL DEFAULT 'PLANNED',
    UNIQUE(company_id, order_number)
);
CREATE TABLE IF NOT EXISTS mfg.quality_results (
    quality_result_id uuid PRIMARY KEY, company_id uuid NOT NULL REFERENCES companies(company_id),
    work_order_id uuid REFERENCES mfg.work_orders(work_order_id), test_code varchar(50) NOT NULL,
    result varchar(30) NOT NULL, measured_value numeric(19,6), recorded_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ai.models (
    model_id uuid PRIMARY KEY, company_id uuid NOT NULL REFERENCES companies(company_id),
    model_code varchar(100) NOT NULL, version varchar(30) NOT NULL, status varchar(30) NOT NULL DEFAULT 'ACTIVE',
    UNIQUE(company_id, model_code, version)
);
CREATE TABLE IF NOT EXISTS ai.predictions (
    prediction_id uuid PRIMARY KEY, company_id uuid NOT NULL REFERENCES companies(company_id),
    model_id uuid REFERENCES ai.models(model_id), entity_type varchar(50) NOT NULL,
    entity_id varchar(100) NOT NULL, score numeric(19,8), created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS audit.events (
    event_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, company_id uuid REFERENCES companies(company_id),
    actor_id varchar(100) NOT NULL, action varchar(50) NOT NULL, entity_type varchar(100) NOT NULL,
    entity_id varchar(100), details jsonb, occurred_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS mst.licenses (
    license_id uuid PRIMARY KEY, company_id uuid REFERENCES companies(company_id),
    license_key varchar(250) NOT NULL UNIQUE, status varchar(30) NOT NULL DEFAULT 'ACTIVE',
    expires_at timestamptz, created_at timestamptz NOT NULL DEFAULT now()
);
